Add ability to change control plane certificates expiration date
epiphany-platform/epiphany pull request #1595
Opened 2020-08-30 02:45 UTC by atsikham

Changes are related to #1302. Documentation is updated with config description.

Cases need to be tested 'at least':
* single-master and HA installations
* `update: true` and `update:false` with different periods, including default
* when certificates are updated, they have the same structure and fields as before update:
```shell
# useful commands
* kubeadm alpha certs check-expiration

# certificates location - /etc/kubernetes/pki/
* openssl x509 -in apiserver.crt -text -noout

# certificates embed to config files also participate in update process
* grep 'client-certificate-data' /etc/kubernetes/controller-manager.conf | awk '{print $2}' | base64 -d | openssl x509 -text
```
* it's possible to renew certs by kubeadm manually: `kubeadm alpha certs renew all`

2020-09-03 15:43 UTC, mkyc approved these changes
Just one question.

2020-09-03 19:52 UTC, atsikham commented on docs/home/CERTIFICATES.md
> +2. update_enddate - whether to update certificates or not
@mkyc at the beginning I wanted to name it just 'update', but it cannot be done as recognized as builtin python method for dictionary. So for sure it should be named with underscore as other parameters and 'enddate' is ept the same as the option of openssl - `openssl x509 -enddate -noout -in apiserver.crt`.
Not sure that `existing` is a correct word as in fact certificates will be regenerated and replaced.

2020-09-03 20:37 UTC, atsikham commented on docs/home/CERTIFICATES.md
> +2. update_enddate - whether to update certificates or not
@mkyc maybe rename this parameter to 'renew', what do you think?

2020-09-04 08:05 UTC, mkyc commented on docs/home/CERTIFICATES.md
> +2. update_enddate - whether to update certificates or not
yeah, `renew` sounds good enough

2020-09-04 08:30 UTC, mkyc approved these changes

2020-09-04 11:20 UTC, przemyslavic commented
/azp run

2020-09-04 12:06 UTC, sk4zuzu requested changes

2020-09-04 14:54 UTC, sk4zuzu commented
@atsikham I've done some testing on the PR.
```
root@x1a1:/etc/kubernetes# find . -type f -path '*/pki/*.crt' | while read FILE; do echo $FILE && openssl x509 -in $FILE -text -noout | grep 'Not After'; done
./pki/front-proxy-client.crt
            Not After : Nov 12 12:13:28 2020 GMT
./pki/apiserver.crt
            Not After : Nov 12 12:13:27 2020 GMT
./pki/etcd/server.crt
            Not After : Nov 12 12:13:28 2020 GMT
./pki/etcd/healthcheck-client.crt
            Not After : Nov 12 12:13:27 2020 GMT
./pki/etcd/ca.crt
            Not After : Sep  2 10:00:49 2030 GMT
./pki/etcd/peer.crt
            Not After : Nov 12 12:13:28 2020 GMT
./pki/ca.crt
            Not After : Sep  2 10:00:48 2030 GMT
./pki/apiserver-etcd-client.crt
            Not After : Nov 12 12:13:27 2020 GMT
./pki/front-proxy-ca.crt
            Not After : Sep  2 10:00:48 2030 GMT
./pki/apiserver-kubelet-client.crt
            Not After : Nov 12 12:13:27 2020 GMT
root@x1a1:/etc/kubernetes# cd ../kubernetes-previous/
root@x1a1:/etc/kubernetes-previous# find . -type f -path '*/pki/*.crt' | while read FILE; do echo $FILE && openssl x509 -in $FILE -text -noout | grep 'Not After'; done
./pki/front-proxy-client.crt
            Not After : Sep  4 10:00:49 2021 GMT
./pki/apiserver.crt
            Not After : Sep  4 11:42:01 2021 GMT
./pki/etcd/server.crt
            Not After : Sep  4 10:00:49 2021 GMT
./pki/etcd/healthcheck-client.crt
            Not After : Sep  4 10:00:50 2021 GMT
./pki/etcd/ca.crt
            Not After : Sep  2 10:00:49 2030 GMT
./pki/etcd/peer.crt
            Not After : Sep  4 10:00:50 2021 GMT
./pki/ca.crt
            Not After : Sep  2 10:00:48 2030 GMT
./pki/apiserver-etcd-client.crt
            Not After : Sep  4 10:00:50 2021 GMT
./pki/front-proxy-ca.crt
            Not After : Sep  2 10:00:48 2030 GMT
./pki/apiserver-kubelet-client.crt
            Not After : Sep  4 10:00:48 2021 GMT
```
The bottom one is default `renew: false`, the upper one is `renew: true` + `expiration_days: 69`.
It seems all certs are updated and the time period is correct.
Good work! :+1:

2020-09-07 06:38 UTC, sk4zuzu approved these changes
LGTM

2020-09-07 09:30 UTC, mkyc approved these changes
LGTM

2020-09-07 13:28 UTC, merged