Multiline support for logs statements in Filebeat
epiphany-platform/epiphany pull request #1611
Opened 2020-09-02 10:58 UTC by rafzei

2020-09-02 13:35 UTC, atsikham requested changes

2020-09-02 13:35 UTC, atsikham commented on docs/home/howto/LOGGING.md
> +More details about multiline options you can find in the official documentation: https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
IMO it's better to specify a hyperlink

2020-09-03 08:00 UTC, rafzei commented on docs/home/howto/LOGGING.md
> +More details about multiline options you can find in the official documentation: https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
That's true, thanks!

2020-09-03 09:37 UTC, atsikham submitted a review, later dismissed
LGTM

2020-09-03 15:27 UTC, mkyc approved these changes
LGTM

2020-09-03 19:39 UTC, atsikham approved these changes

2020-09-04 06:01 UTC, merged