Fixed autoscaler deployment, resource group name change, README updated
epiphany-platform/epiphany pull request #1623
Opened 2020-09-04 11:10 UTC by mum0l

2020-09-08 08:16 UTC, mkyc commented on docs/design-docs/eks/terraform-scripts/terraform.tfvars
> +account_id = "540350320930"
remove it

2020-09-08 10:31 UTC, pyrkamarcin requested changes

2020-09-08 12:46 UTC, mum0l commented on docs/design-docs/eks/terraform-scripts/aws-resource-groups.tf
> +  name = "resource-group-${random_string.random.result}"
For now, we can leave it as it is. Lets adjust those vars in another task related to integration.

2020-09-08 12:51 UTC, pyrkamarcin approved these changes

2020-09-08 12:59 UTC, mum0l commented on docs/design-docs/eks/terraform-scripts/terraform.tfvars
> +account_id = "540350320930"
Variable moved into secret vars.

2020-09-14 09:43 UTC, mkyc approved these changes

2020-09-14 09:46 UTC, merged