epicli upgrade fails on Ubuntu with downgrading kubernetes-cni package
epiphany-platform/epiphany pull request #1666
Opened 2020-09-16 21:49 UTC by to-bar

2020-09-16 21:50 UTC, to-bar commented
/azp run

2020-09-17 06:33 UTC, atsikham approved these changes
LGTM

2020-09-17 06:34 UTC, pyrkamarcin submitted a review, later dismissed

2020-09-17 09:52 UTC, sk4zuzu requested changes

2020-09-17 09:52 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/kubernetes/Debian/install-packages.yml
> +          {{ target_packages.keys() | zip(target_packages.values()) | map('join', '=') | list }}
```suggestion
          {{ target_packages.items() | map('join', '=') | list }}
```

2020-09-17 10:21 UTC, sk4zuzu approved these changes
LGTM

2020-09-17 10:34 UTC, atsikham approved these changes
LGTM

2020-09-17 10:37 UTC, merged