Fix SSH tunnel from epicli container
epiphany-platform/epiphany pull request #1686
Opened 2020-09-18 15:19 UTC by to-bar

- Add procps package to have ps command
- Improve sshtunnel role

2020-09-18 15:19 UTC, to-bar commented
/azp run

2020-09-18 15:37 UTC, sk4zuzu requested changes

2020-09-18 15:37 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
> +  if sudo lsof -i:"$LOCAL_PORT"; then
I'm concerned about this sudo stuff! We shouldn't be doing that. 🐬

2020-09-18 15:49 UTC, sk4zuzu requested changes

2020-09-18 15:49 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/tasks/setup.yml
> +    -o "ServerAliveInterval 30" -o "ServerAliveCountMax 5"
```suggestion
    -o ServerAliveInterval=30 -o ServerAliveCountMax=5
```

2020-09-18 15:49 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/tasks/setup.yml
> +    -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"
```suggestion
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
```

2020-09-18 15:49 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/tasks/setup.yml
> +    -o "ServerAliveInterval 30" -o "ServerAliveCountMax 5"
I'd keep it consistent :+1:

2020-09-18 15:58 UTC, sk4zuzu submitted a review, later dismissed
LGTM

2020-09-18 19:50 UTC, to-bar commented
/azp run

2020-09-18 23:21 UTC, sk4zuzu requested changes
:thinking:

2020-09-18 23:21 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
>  #!/bin/bash
This will work across bigger number of operating systems! (for example in NixOS ;P)
```suggestion
#!/usr/bin/env bash
```

2020-09-18 23:21 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
Thanks to that a function can be used inside a subshell :+1: (assuming we are using BASH):
```suggestion

export -f is_port_available

```

2020-09-18 23:21 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
> +  if timeout 20 sh -c "until nc -z 127.0.0.1 $LOCAL_PORT; do sleep 0.5; done"; then
How about reusing the function? :thinking: 
```suggestion
  if timeout 20 bash -c "while is_port_available; do sleep 0.5; done"; then
```

2020-09-18 23:21 UTC, sk4zuzu commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
> +  if test -f $AUTOSSH_PIDFILE; then
How about (for consistency reasons)? :thinking: 
```suggestion
  if [ -f "$AUTOSSH_PIDFILE" ]; then
```

2020-09-19 15:10 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/sshtunnel/files/tunnel.sh
> +  nc -z 127.0.0.1 "$port" && return 1 || return 0 # 0 if port is available
Another great review! 👍 I've decided to remove the script and use pure Ansible 😉

2020-09-19 18:04 UTC, sk4zuzu approved these changes
🥰

2020-09-20 10:01 UTC, seriva approved these changes
Nice addition using AUTOSSH_PIDFILE for process management, I approve:)

2020-09-21 07:51 UTC, merged