Removed unused security rules fields.
epiphany-platform/epiphany pull request #1714
Opened 2020-09-30 10:48 UTC by seriva

2020-09-30 11:38 UTC, pyrkamarcin submitted a review, later dismissed

2020-10-01 08:51 UTC, pyrkamarcin submitted a review, later dismissed

2020-10-01 10:43 UTC, atsikham requested changes
In general some day I would like to see code formatted according to PEP8. Not sure if vscode can do this, but it's for sure possible in pycharm.

LGTM, but a few changes requested.

2020-10-01 10:43 UTC, atsikham commented on core/src/epicli/cli/engine/providers/aws/InfrastructureBuilder.py
> +                    if self.rule_exists_in_list(security_group.specification.rules, rule) == False:
May be `if not`?

2020-10-01 10:43 UTC, atsikham commented on core/src/epicli/data/aws/terraform/infrastructure/security-group.j2
>  }
Newline

2020-10-01 14:25 UTC, seriva commented on core/src/epicli/cli/engine/providers/aws/InfrastructureBuilder.py
> +                    if self.rule_exists_in_list(security_group.specification.rules, rule) == False:
Fixed

2020-10-01 14:25 UTC, seriva commented on core/src/epicli/data/aws/terraform/infrastructure/security-group.j2
>  }
fixed

2020-10-01 14:26 UTC, seriva commented
Yes we can set up PEP8 in VSCode easily, I am pretty sure its even in the backlog somewhere.

2020-10-01 14:48 UTC, atsikham approved these changes

2020-10-02 06:49 UTC, erzetpe approved these changes

2020-10-02 06:57 UTC, merged