Fix undefined variable, make jvm settings configurable
epiphany-platform/epiphany pull request #1740
Opened 2020-10-06 14:34 UTC by rafzei

2020-10-06 14:56 UTC, to-bar approved these changes

2020-10-06 14:56 UTC, to-bar commented on core/src/epicli/data/common/defaults/configuration/logging.yml
> +  max_heap_space: -Xmx1g
```suggestion
  init_heap_size: -Xms1g
  max_heap_size: -Xmx1g
```

2020-10-06 14:56 UTC, to-bar commented on core/src/epicli/data/common/defaults/configuration/opendistro-for-elasticsearch.yml
> +  max_heap_space: -Xmx1g
```suggestion
  init_heap_size: -Xms1g
  max_heap_size: -Xmx1g
```

2020-10-06 15:06 UTC, to-bar approved these changes

2020-10-06 19:50 UTC, to-bar requested changes

2020-10-06 19:50 UTC, to-bar commented on core/src/epicli/data/common/defaults/configuration/logging.yml
> +  max_heap_size: -Xmx1g
```suggestion
  jvm_options:
    Xmx: 1g # see https://www.elastic.co/guide/en/elasticsearch/reference/7.9/heap-size.html
```

2020-10-06 19:50 UTC, to-bar commented on core/src/epicli/data/common/defaults/configuration/opendistro-for-elasticsearch.yml
> +  max_heap_size: -Xmx1g
```suggestion
  jvm_options:
    Xmx: 1g # see https://www.elastic.co/guide/en/elasticsearch/reference/7.9/heap-size.html
```

2020-10-06 19:50 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/jvm.options.j2
> +{{ specification.max_heap_size }}
```suggestion
{# Xms = Xmx by purpose, must be equal #}
-Xms{{ specification.jvm_options.Xmx }}
-Xmx{{ specification.jvm_options.Xmx }}
```

2020-10-07 07:09 UTC, to-bar approved these changes

2020-10-07 07:15 UTC, rpudlowski93 approved these changes
LGTM

2020-10-07 07:16 UTC, merged