raise disk space for repository machine [#1640]
epiphany-platform/epiphany pull request #1768
Opened 2020-10-13 20:25 UTC by ar3ndt

2020-10-14 10:37 UTC, to-bar requested changes
Please update the changelog since we've already released 0.8.0rc1 and this change affects this version.

2020-10-15 12:17 UTC, to-bar requested changes

2020-10-15 12:17 UTC, to-bar commented on CHANGELOG-0.8.md
> +- [#1640](https://github.com/epiphany-platform/epiphany/issues/1640) - Default disk size for repository machine increased to 64gb for both aws and azure
```suggestion
- [#1640](https://github.com/epiphany-platform/epiphany/issues/1640) - Default disk size for repository machine increased to 64 GB (AWS and Azure)
```

2020-10-15 12:25 UTC, to-bar approved these changes

2020-10-15 12:54 UTC, rafzei approved these changes

2020-10-15 12:59 UTC, seriva approved these changes

2020-10-15 13:46 UTC, merged