kubernetes_master: introduce self-updating imageRepository
epiphany-platform/epiphany pull request #1837
Opened 2020-11-07 21:11 UTC by sk4zuzu

This is the fourth PR in series. :+1::innocent:

In this PR we fix switching between custom image registry and other methods by modifying both static pod definitions and kube-system deamonsets, deployments and statefulsets. This may be a little controversial, please review thoroughly. :hugs:

2020-11-10 08:25 UTC, rafzei submitted a review, later dismissed
Not tested but its looks ok for me

2020-11-12 12:10 UTC, to-bar requested changes

2020-11-12 12:10 UTC, to-bar commented on docs/home/howto/CLUSTER.md
> +- the repository data (apt or yum packages) is served from Apache2 HTTP server exactly as structured in the offline package
```suggestion
- the repository data (including apt or yum repository) is served from HTTP server and structured exactly as in the offline package
```

2020-11-12 12:10 UTC, to-bar commented on docs/home/howto/CLUSTER.md
> +- the image registry data is loaded into and served from standard docker registry implementation
```suggestion
- the image registry data is loaded into and served from standard Docker registry implementation
```

2020-11-12 12:19 UTC, atsikham approved these changes
I had questions about usage of `none://` and updating only `kube-system`, clarified them with @to-bar. LGTM
* `spliturl` requires a protocol, so this is just dummy / fake string
* other namespaces that are managed by Epiphany code should be updated during `epicli apply` for example by applications role

2020-11-12 13:18 UTC, sk4zuzu commented on docs/home/howto/CLUSTER.md
> +  custom_repository_url: "http://10.50.2.1:8080/epirepo"
I think this should answer your question https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/ansible/playbooks/roles/helm/defaults/main.yml#L6 :+1:

By default we use 80 and the tunnel, but if we set custom repo this port can be any number and  it's later used across the whole ansible codebase. :innocent:

2020-11-12 13:29 UTC, to-bar commented on docs/home/howto/CLUSTER.md
> +  custom_repository_url: "http://10.50.2.1:8080/epirepo"
Thanks 👍

2020-11-12 13:30 UTC, to-bar approved these changes

2020-11-12 13:35 UTC, atsikham approved these changes

2020-11-12 14:01 UTC, merged