custom_image_registry_address: add info how to disable repository vm
epiphany-platform/epiphany pull request #1850
Opened 2020-11-12 18:41 UTC by sk4zuzu

This is the fifth and the last PR in series. :+1::innocent:

Just a documentation update.

2020-11-12 18:50 UTC, to-bar requested changes

2020-11-12 18:50 UTC, to-bar commented on docs/home/howto/CLUSTER.md
> +Epiphany by default creates "repository" virtual nachine in cloud environments. When custom repository and registry are used there is no need for additional empty virtual machine.
```suggestion
By default Epiphany creates "repository" virtual machine in cloud environments. When custom repository and registry are used there is no need for additional empty VM.
```

2020-11-12 19:14 UTC, sk4zuzu commented on docs/home/howto/CLUSTER.md
> +  custom_image_registry_address: "<public-ip-address>:5000"
```suggestion
  custom_image_registry_address: "<ip-address>:5000"
```

2020-11-12 19:14 UTC, sk4zuzu commented on docs/home/howto/CLUSTER.md
> +  custom_repository_url: "http://<public-ip-address>:8080/epirepo"
```suggestion
  custom_repository_url: "http://<ip-address>:8080/epirepo"
```

2020-11-12 19:17 UTC, to-bar submitted a review, later dismissed

2020-11-12 19:38 UTC, sk4zuzu commented on docs/home/howto/CLUSTER.md
> +By default Epiphany creates "repository" virtual machine in cloud environments. When custom repository and registry are used there is no need for additional empty VM.
```suggestion
By default Epiphany creates "repository" virtual machine for cloud environments. When custom repository and registry are used there is no need for additional empty VM.
```

2020-11-12 19:39 UTC, to-bar approved these changes

2020-11-13 07:55 UTC, rafzei approved these changes

2020-11-13 08:41 UTC, merged