Include default vars to filebeat's upgrade role
epiphany-platform/epiphany pull request #1878
Opened 2020-11-26 23:47 UTC by rpudlowski93

- PR releated to failed test in task #1833 
- Default vars included to filebeat upgrade role from filebeat role
- Filebeat chart name moved from specification to defaults

2020-11-27 08:37 UTC, to-bar requested changes

2020-11-27 08:37 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/filebeat.yml
> +- name: Filebeat | Load defaults from filebat role
```suggestion
- name: Filebeat | Load defaults from filebeat role
```

2020-11-27 12:07 UTC, to-bar approved these changes

2020-11-27 13:26 UTC, przemyslavic commented
@rpudlowski93 I found a bug while testing fix for failing upgrades [#1875](https://github.com/epiphany-platform/epiphany/issues/1875) (PR [#1876](https://github.com/epiphany-platform/epiphany/pull/1876)). I deployed a cluster without kubernetes and helm. During upgrade it fails on task `Get information about helm releases`. The entire block `Filebeat as DaemonSet | Prepare fact about helm release` should be run conditionally (when k8s_as_cloud_service). Same for node exporter.

2020-11-30 08:40 UTC, przemyslavic commented
/azp run

2020-11-30 12:24 UTC, przemyslavic commented
/azp run

2020-12-01 14:35 UTC, to-bar approved these changes

2020-12-01 15:10 UTC, atsikham approved these changes

2020-12-01 15:13 UTC, merged