Istio feature
epiphany-platform/epiphany pull request #1925
Opened 2020-12-18 14:01 UTC by rpudlowski93

- Istio installation using Istio operator

2020-12-18 15:18 UTC, seriva commented on core/src/epicli/data/common/defaults/configuration/applications.yml
> +    enabled: yes
Dont enable by default.

2020-12-18 15:18 UTC, seriva commented on core/src/epicli/.devcontainer/Dockerfile
> +    && echo "Installing istioctl binary ..." \
Also add this to the main [deployment container](https://github.com/epiphany-platform/epiphany/blob/develop/Dockerfile) in the root of the repo

2020-12-22 18:02 UTC, to-bar requested changes

2020-12-22 18:02 UTC, to-bar commented on docs/home/howto/ISTIO.md
> +You may need to make the application accessible from outside of your Kubernetes cluster. An Istio Gateway which was deployed using default profile is used for this purpose. Define the the ingress gat
```suggestion
You may need to make an application accessible from outside of your Kubernetes cluster. An Istio Gateway which was deployed using default profile is used for this purpose. Define the ingress gateway deploying gateway and virtual service specification. The gateway specification describes the L4-L6 properties of a load balancer and the virtual service specification describes the L7 properties of a load balancer.
```

2020-12-28 12:07 UTC, seriva approved these changes

2020-12-28 13:19 UTC, rafzei submitted a review, later dismissed
:+1:

2020-12-29 09:26 UTC, to-bar requested changes

2020-12-29 09:26 UTC, to-bar commented on docs/home/howto/ISTIO.md
> +The default Istio installation use automcatic sidecar injection. You need to label the namespace where application will be hosted:
```suggestion
The default Istio installation uses automcatic sidecar injection. You need to label the namespace where application will be hosted:
```

2020-12-29 09:30 UTC, to-bar approved these changes

2020-12-30 09:26 UTC, przemyslavic commented
/azp run

2021-01-04 08:55 UTC, ar3ndt reviewed
I have met issue during installation @rhel. Seems like package is unavailable: istio/proxyv2:1.8.1

2021-01-04 09:01 UTC, przemyslavic commented
@ar3ndt when exactly was that? On Wednesday I was able to install Istio on all environments (`AWS` / `Azure` x `Ubuntu` / `RHEL`).

2021-01-04 09:06 UTC, sk4zuzu requested changes

2021-01-04 09:06 UTC, sk4zuzu commented on docs/home/howto/ISTIO.md
> +Open source platform which allows you to run service mesh for distributed microservice architecture. It allows to connect, manage and run secure connections between microservices and brings a lot of
Isn't this better? :thinking: 
```suggestion
Open source platform which allows you to run service mesh for distributed microservice architecture. It allows to connect, manage and run secure connections between microservices and brings lots of features such as load balancing, monitoring and service-to-service authentication without any changes in service code. Read more about Istio [here](https://istio.io/latest/docs/concepts/what-is-istio/).
```

2021-01-04 09:17 UTC, ar3ndt commented
> @ar3ndt when exactly was that? On Wednesday I was able to install Istio on all environments (`AWS` / `Azure` x `Ubuntu` / `RHEL`).

Im doing it again - hopefully it was temporary docker hub issue.

2021-01-04 10:15 UTC, ar3ndt commented
> > @ar3ndt when exactly was that? On Wednesday I was able to install Istio on all environments (`AWS` / `Azure` x `Ubuntu` / `RHEL`).
> 
> Im doing it again - hopefully it was temporary docker hub issue.

it is fine now.

2021-01-04 13:36 UTC, seriva approved these changes

2021-01-04 14:47 UTC, sk4zuzu approved these changes
:heart_eyes:

2021-01-04 14:53 UTC, merged