rabbitmq: ensuring rmq service is running before rabbitmqctl is executed (fix)
epiphany-platform/epiphany pull request #1932
Opened 2021-01-04 16:56 UTC by sk4zuzu

Tested on Ubuntu and CentOS.

2021-01-05 04:55 UTC, atsikham requested changes

2021-01-05 04:55 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/rabbitmq/tasks/main.yml
> +  systemd:
The `service` module is used in all other places of the role. I would do it the same way.

2021-01-05 09:12 UTC, atsikham approved these changes

2021-01-07 12:18 UTC, przemyslavic approved these changes

2021-01-07 12:23 UTC, merged