add condition to install filebeat if logging is defined
epiphany-platform/epiphany pull request #1941
Opened 2021-01-11 14:55 UTC by ar3ndt

2021-01-13 09:33 UTC, to-bar requested changes

2021-01-13 09:33 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/filebeat/tasks/main.yml
> +      - groups.logging is defined
```suggestion
      - groups.logging is defined
      - groups.logging | length > 0
```

2021-01-13 09:35 UTC, to-bar commented
Please update changelog file.

2021-01-14 13:02 UTC, mkyc commented
I already connected issue with PR in ZH.

2021-01-21 09:23 UTC, erzetpe approved these changes

2021-01-21 12:01 UTC, mkyc approved these changes

2021-01-22 11:21 UTC, to-bar approved these changes

2021-01-25 12:56 UTC, merged