[BUG] Allow traffic from loadbalancer to kubernetes subnet
epiphany-platform/epiphany pull request #1980
Opened 2021-01-18 20:09 UTC by rpudlowski93

PR related to BUG reported in #1959 

- Problem exist only on AWS. On Azure, there is by default rules which allow all traffic in vnet.
- Additional rule added and tested using connection from Loadbalancer instance (HAProxy) to application in kubernetes cluster.

2021-01-19 06:02 UTC, atsikham requested changes

2021-01-19 06:02 UTC, atsikham commented on core/src/epicli/data/aws/defaults/infrastructure/virtual-machine.yml
> +     - name: load-balacner-subnet-traffic
```suggestion
     - name: load-balancer-subnet-traffic
```

2021-01-19 11:38 UTC, atsikham requested changes
Please update changelog

2021-01-19 17:02 UTC, atsikham approved these changes

2021-01-20 15:40 UTC, erzetpe approved these changes

2021-01-20 16:44 UTC, merged