[BACKPORT] Upgrade Zookeeper to v3.5.8
epiphany-platform/epiphany pull request #2083
Opened 2021-02-26 09:32 UTC by rpudlowski93

Related to task: #1927

2021-02-26 12:59 UTC, atsikham requested changes
Is the file core/src/epicli/data/common/ansible/playbooks/roles/zookeeper/files/snapshot.0 necessary here?

2021-02-26 13:00 UTC, erzetpe approved these changes

2021-02-26 13:46 UTC, atsikham approved these changes

2021-02-27 11:59 UTC, rpudlowski93 commented
> Is the file core/src/epicli/data/common/ansible/playbooks/roles/zookeeper/files/snapshot.0 necessary here?

Yes, it is! This is the same solution which I used in 0.8 and 0.9 version of Epiphany. It is necessary to run zookeeper with any snapshot file and from time to time there can be situation when snapshot file is not present. There is no better solution, there was already some discussions about it. :) ... but good question :)

2021-02-27 11:59 UTC, merged