Documentation how to handle data in Opendistro for Elasticsearch
epiphany-platform/epiphany pull request #2107
Opened 2021-03-09 11:00 UTC by plirglo

Documentation how to handle data in Opendistro for Elasticsearch

2021-03-11 10:34 UTC, seriva requested changes

2021-03-11 10:34 UTC, seriva commented on docs/home/howto/LOGGING.md
> +Elasticsearch stores data using JSON documents, and an Index is a collection of documents. As in every database it's crutial to correctly maintain data in this one. It's almost impossible to deliver
Before going to production the configuration should be tailor to the project needs

2021-03-11 10:34 UTC, seriva commented on docs/home/howto/LOGGING.md
> +The main and most importand decisions to take before you deploy cluster are:
important

2021-03-11 10:34 UTC, seriva commented on docs/home/howto/LOGGING.md
> +These parameters are defined in yaml file and it's important to create big enough cluster.
a big enough cluster

2021-03-17 09:06 UTC, rafzei approved these changes

2021-03-22 10:10 UTC, seriva approved these changes

2021-03-22 10:12 UTC, merged