Added more requirements for ARM.
epiphany-platform/epiphany pull request #2108
Opened 2021-03-09 14:12 UTC by seriva

2021-03-11 14:39 UTC, atsikham requested changes
LGTM with a small comment

2021-03-11 14:39 UTC, atsikham commented on docs/design-docs/arm/arm.md
> +This document outlines an aproach to add (partial) ARM support to Epicli. The requirments:
```suggestion
This document outlines an aproach to add (partial) ARM support to Epicli. The requirements:
```

2021-03-12 08:52 UTC, mkyc approved these changes

2021-03-12 09:36 UTC, atsikham approved these changes

2021-03-12 12:00 UTC, merged