additional retry cmds
epiphany-platform/epiphany pull request #2187
Opened 2021-04-07 19:50 UTC by ar3ndt

2021-04-08 15:58 UTC, to-bar requested changes
Please add entry to changelog.

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/common.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-08 15:58 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/ubuntu-18.04/common.sh
> +	local retries="3"
```suggestion
	local retries=3
```

2021-04-09 07:45 UTC, to-bar approved these changes

2021-04-09 08:31 UTC, atsikham approved these changes

2021-04-09 19:18 UTC, merged