add Ubuntu ARM supported packages doc list
epiphany-platform/epiphany pull request #2239
Opened 2021-04-21 12:15 UTC by ar3ndt

2021-04-21 14:38 UTC, seriva requested changes

2021-04-21 14:38 UTC, seriva commented on CHANGELOG-0.11.md
> +- [#2230](https://github.com/epiphany-platform/epiphany/issues/2230) - [Ubuntu] Ensure that there are packages for all required components available for ARM architecture on Ubuntu
This is not needed as its just research.

2021-04-23 08:31 UTC, mkyc commented
Change it to merge to ARM not develop.

2021-04-27 07:50 UTC, seriva approved these changes

2021-04-27 11:56 UTC, merged