Elasticsearch: Use static ports and get settings from config file
epiphany-platform/epiphany pull request #2245
Opened 2021-04-22 16:17 UTC by to-bar

2021-04-22 16:17 UTC, to-bar commented
/azp run

2021-04-22 16:33 UTC, to-bar commented
/azp run

2021-04-27 07:31 UTC, erzetpe submitted a review, later dismissed

2021-04-27 07:40 UTC, atsikham requested changes

2021-04-27 07:40 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/upgrade/tasks/opendistro_for_elasticsearch/upgrade-elasticsearch.yml
> +  when: elasticsearch_state.changed == true
```suggestion
  when: elasticsearch_state.changed
```

2021-04-27 07:47 UTC, atsikham approved these changes

2021-04-27 07:47 UTC, erzetpe approved these changes

2021-04-27 08:13 UTC, merged