[Fix] Vault image updated to version 1.7.0
epiphany-platform/epiphany pull request #2268
Opened 2021-04-29 11:27 UTC by rpudlowski93

Fix for the issue in the task #2241

- Hashicorp Vault image updated to version 1.7.0

2021-04-29 11:29 UTC, przemyslavic commented
/azp run

2021-05-03 20:34 UTC, atsikham requested changes
PR should be modified, check commits and changed files.

2021-05-04 10:01 UTC, atsikham approved these changes

2021-05-04 10:52 UTC, seriva approved these changes

2021-05-04 10:53 UTC, merged