Fix filebeat daemonset template
epiphany-platform/epiphany pull request #2276
Opened 2021-05-03 20:27 UTC by atsikham

2021-05-04 13:02 UTC, rafzei requested changes
What about changelog?

2021-05-04 13:02 UTC, rafzei commented on docs/home/howto/LOGGING.md
> +## Multiline support for Filebeat logs
If you want to change this header you have change reference here: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/HOWTO.md

2021-05-04 13:02 UTC, rafzei commented on docs/home/howto/LOGGING.md
> +## Export Elasticsearch data to CSV format
If you want to change this header you have change reference here: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/HOWTO.md

2021-05-04 13:02 UTC, rafzei commented on docs/home/howto/LOGGING.md
> +## Opendistro for Elasticsearch data management
If you want to change this header you have change reference here: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/HOWTO.md

2021-05-04 22:06 UTC, mkyc approved these changes

2021-05-05 08:01 UTC, rafzei approved these changes

2021-05-05 09:00 UTC, merged