Added arm64 documentation.
epiphany-platform/epiphany pull request #2287
Opened 2021-05-05 14:17 UTC by seriva

2021-05-07 12:06 UTC, rafzei requested changes
Looks good but I've added minor changes

2021-05-07 12:06 UTC, rafzei commented on docs/home/ARM.md
> +From Epiphany 1.1.0 preliminary support for the ```arm64``` architecture was added. As the ```arm64``` architecture is relatively new to the datacenter at the time of writing only a subset of provide
```suggestion
From Epiphany v1.1.0 preliminary support for the ```arm64``` architecture was added. As the ```arm64``` architecture is relatively new to the datacenter at the time of writing only a subset of providers, operating system, components and applications are supported. Support will be extended in the future when there is a need for it.
```

2021-05-07 12:06 UTC, rafzei commented on docs/home/ARM.md
> +- While not defined in any of the component configurations, the ```elasticsearch_curator``` role us currently not supported on ```arm64``` and should be removed from the ```feature-mapping``` configu
```suggestion
- While not defined in any of the component configurations, the ```elasticsearch_curator``` role is currently not supported on ```arm64``` and should be removed from the ```feature-mapping``` configuration if defined.
```

2021-05-10 07:19 UTC, rafzei submitted a review, later dismissed

2021-05-10 08:06 UTC, plirglo commented on docs/home/ARM.md
> +- For the ```postgresql``` component the ```pgpool``` and ```pgbouncer``` extensions for load-balancing and replication are not jet supported on ```arm64```. These should be disabled in the ```postgr
Typo: "yet" instead "jet"

2021-05-10 08:06 UTC, plirglo commented on docs/home/ARM.md
> +- Important is to specify the right ```arm64``` OS image which currently is only ```CentOS 7.9.2009 aarch64```.
Maybe correct instead right? (just suggestion)

2021-05-10 08:06 UTC, plirglo commented on docs/home/ARM.md
> +| Providers | CentOS 7.x | RedHat 7.x | Ubuntu 18.04 |
I would rather use singular (Provider, Component, Application) in all tables, or at least keep them consistent

2021-05-10 13:26 UTC, rafzei submitted a review, later dismissed
:rocket:

2021-05-10 13:29 UTC, plirglo commented on docs/home/ARM.md
> +From Epiphany v1.1.0 preliminary support for the ```arm64``` architecture was added. As the ```arm64``` architecture is relatively new to the datacenter at the time of writing only a subset of provid
operating system**s**

2021-05-10 13:32 UTC, plirglo approved these changes

2021-05-10 13:32 UTC, rafzei approved these changes

2021-05-10 13:38 UTC, merged