Update Python dependencies resolving
epiphany-platform/epiphany pull request #2301
Opened 2021-05-06 18:33 UTC by seriva

- Updated first line dependency azure-cli from 
- Updated all 3 line dependencies solving the following security issues:
  1: jinja2 from 2.11.2 to 2.11.3 as its a direct dependency
  2: urllib3 - 1.26.2 to 1.26.4
  3: cryptography is a requirement and needs >= 3.2 if possible.
- Updated of the licenses.py
- Updated of the COMPONENTS.md

2021-05-07 15:50 UTC, to-bar requested changes

2021-05-07 15:50 UTC, to-bar commented on core/src/epicli/gen-dependency-info.py
> +    # To re-generate run 'python gen-dependency-info.py 'GitHub PAC' ' from the project root.
```suggestion
    # To re-generate run 'python gen-dependency-info.py <GitHub_PAT>' from the project root.
```

2021-05-07 15:50 UTC, to-bar commented on core/src/epicli/cli/licenses.py
> +# To re-generate run 'python gen-dependency-info.py 'GitHub PAC' ' from the project root.
```suggestion
# To re-generate run 'python gen-dependency-info.py <GitHub_PAT>' from the project root.
```

2021-05-07 16:15 UTC, to-bar commented
How about updating changelog?

2021-05-10 09:08 UTC, seriva commented
> How about updating changelog?

Added.

2021-05-11 07:39 UTC, plirglo approved these changes

2021-05-11 07:41 UTC, atsikham approved these changes
LGTM

2021-05-12 06:56 UTC, to-bar approved these changes

2021-05-12 07:47 UTC, merged