[0.9] RHUI client certificate refresh for RHEL 7-RAW images
epiphany-platform/epiphany pull request #2315
Opened 2021-05-11 10:44 UTC by plirglo

2021-05-11 10:45 UTC, przemyslavic commented
/azp run

2021-05-11 10:51 UTC, seriva reviewed
How does this effect AWS or offline installations as this seems universal?

2021-05-11 10:57 UTC, przemyslavic commented
I am going to test it before merging.

Edit: It fails for AWS.
```
"Executing: yum update -y --disablerepo=* --enablerepo=*microsoft*", "Loaded plugins: amazon-id, search-disabled-repos", "There are no enabled repos.", " Run \"yum repolist all\" to see the repos you have.", " To enable Red Hat Subscription Management repositories:", "     subscription-manager repos --enable <repo>", " To enable custom repositories:", "     yum-config-manager --enable <repo>", "ERROR: Command failed: yum update -y --disablerepo=* --enablerepo=*microsoft*"]}
```

2021-05-11 12:02 UTC, przemyslavic commented
/azp run

2021-05-11 12:44 UTC, przemyslavic commented
/azp run

2021-05-12 07:37 UTC, przemyslavic commented
/azp run

2021-05-12 08:55 UTC, przemyslavic commented
/azp run

2021-05-12 11:24 UTC, to-bar requested changes

2021-05-12 11:24 UTC, to-bar commented on CHANGELOG-0.9.md
> +- [#2312](https://github.com/epiphany-platform/epiphany/issues/2312) - [RedHat/Azure] RHUI client certificate expired for RHEL 7-RAW images
```suggestion
- [#2312](https://github.com/epiphany-platform/epiphany/issues/2312) - [RHEL/Azure] RHUI client certificate expired for RHEL 7-RAW images
```

2021-05-12 11:24 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +fi
```suggestion
# Update RHUI client package to update expired certificate [Epiphany issue #2312]
if is_repo_enabled "microsoft"; then
    run_cmd_with_retries yum update -y --disablerepo='*' --enablerepo='rhui-microsoft-azure-rhel*' 3
fi
```

2021-05-12 11:46 UTC, przemyslavic commented
/azp run

2021-05-12 12:12 UTC, to-bar approved these changes

2021-05-12 12:31 UTC, przemyslavic approved these changes

2021-05-12 13:03 UTC, seriva approved these changes

2021-05-12 13:05 UTC, merged