Repository documentation.
epiphany-platform/epiphany pull request #2395
Opened 2021-06-24 13:06 UTC by seriva

2021-06-24 15:55 UTC, mkyc submitted a review, later dismissed

2021-06-25 13:09 UTC, to-bar requested changes

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +2. Setup Epiphany repository
```suggestion
2. Set up Epiphany repository (create `epirepo` and start HTTP server)

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +   - Backup and disable system package repositories
```suggestion
   - Back up and disable system package repositories

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +   - Restore backup of system package repositories
```suggestion
   - Restore original package repositories from the backup

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +4. Teardown Epiphany repository
```suggestion
6. Stop Epiphany repository (optionally removing data)

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +Downloading requirements is one of the most sensitive steps in deploying a new cluster because lots of resources are beeing downloaded from various repositories and sources.
```suggestion
Downloading requirements is one of the most sensitive steps in deploying a new cluster because lots of resources are being downloaded from various sources.

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +When you see the following output from Epicli requirements are beeing downloaded:
```suggestion
When you see the following output from epicli, requirements are being downloaded:
```
About uppercase, IMO `Epiphany` as project name can/should be written starting with capital but `epicli` as tool name could be written lowercase, just like `Kubernetes` vs `kubectl`.

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +As noted this process can take a long time depending on the connection and as downloading requirements is beeing done by a shell script the ```Ansible``` process cannot return any realtime informatio
```suggestion
As noted this process can take a long time depending on the connection and as downloading requirements is being done by a shell script, the ```Ansible``` process cannot return any realtime information.

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +As stated to view the progress during the downloading one can SSH into the repository machine and run:
```suggestion
To view the progress during the downloading (realtime output from the logs), one can SSH into the repository machine and run:

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +
```suggestion
```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +This directory holds all the files beeing downloaded and removing it makes sure that there are no locks anymore or temperary files which might interfere with the restarted download progress.
```suggestion
This directory holds all the files being downloaded and removing it makes sure that there are no corrupted or temporary files which might interfere with the restarted download process.
```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +If you want to re-download the requirements but the process finished succesfully before you might need to remove the following file:
```suggestion
If you want to re-download the requirements but the process finished successfully before, you might need to remove the following file:

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +When this file is present it enforces skiping re-downloading requirements for a defined amount of time (default 2 hours).
```suggestion
When this file is present and it isn't older than defined amount of time (2 hours by default), it enforces skipping re-downloading requirements.

```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +If during the component installation an issue will arrise (installation or connection issue E.g) it might be the case that the cluster machines are left in a state where step 5 of the repository life
```suggestion
If during the component installation an issue will arise (e.g. network issue), it might be the case that the cluster machines are left in a state where step 5 of the repository lifecycle is not run. This will leave the machines with a broken repository setup making re-running ```epicli apply``` impossible as noted in issue [#2324](https://github.com/epiphany-platform/epiphany/issues/2324).
```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +/tmp/epi-repository-setup-scripts/enable-system-repos.sh
```suggestion
# Re-enable system repositories
/tmp/epi-repository-setup-scripts/enable-system-repos.sh
# Disable epirepo
/tmp/epi-repository-setup-scripts/disable-epirepo-client.sh
```

2021-06-25 13:09 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +To work arround this issue for now one can execute the following script on every cluster machine to restore the original repository setup:
```suggestion
To restore the original repository setup on a machine, you can execute the following scripts:
```

2021-06-25 13:51 UTC, mkyc submitted a review, later dismissed

2021-06-25 13:52 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +
```suggestion
```

2021-06-25 13:52 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +
```suggestion
```

2021-06-25 13:52 UTC, to-bar commented on docs/home/howto/REPOSITORY.md
> +
```suggestion
```

2021-06-25 13:54 UTC, to-bar approved these changes, later dismissed

2021-06-25 13:57 UTC, mkyc approved these changes

2021-06-25 14:00 UTC, to-bar approved these changes

2021-06-25 14:04 UTC, merged