Automatic open distro clusterization
epiphany-platform/epiphany pull request #2426
Opened 2021-07-12 13:04 UTC by erzetpe

The aim of this PR is to drop not used non-cluster Epiphany Open Distro deployment and provide only clustered option.

2021-07-12 14:12 UTC, plirglo requested changes

2021-07-12 14:12 UTC, plirglo commented on docs/home/howto/DATABASES.md
> +configuration for Open Distro is not supported.
```Option to configure the non-clustered installation of more than one node is not supported.
```

2021-07-13 09:08 UTC, to-bar requested changes

2021-07-13 09:08 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/tasks/configure-es.yml
> +      {%- if groups['opendistro_for_elasticsearch'] | length > 1 -%}
```suggestion
      {%- if groups[current_group_name] | length > 1 -%}
```

2021-07-13 09:08 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +{% if groups['opendistro_for_elasticsearch'] | length > 1 -%}
```suggestion
{% if groups[current_group_name] | length > 1 -%}
```

2021-07-13 09:08 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +
```suggestion
```

2021-07-13 09:08 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +  {% if groups['opendistro_for_elasticsearch'] | length > 1 %}
```suggestion
  {% if groups[current_group_name] | length > 1 %}
```

2021-07-13 09:12 UTC, to-bar reviewed
Please update the changelog

2021-07-13 09:46 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/tasks/configure-es.yml
> +      {%- if groups['opendistro_for_elasticsearch'] | length > 1 -%}
Done.

2021-07-13 09:47 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +{% if groups['opendistro_for_elasticsearch'] | length > 1 -%}
Done.

2021-07-13 09:47 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +  {% if groups['opendistro_for_elasticsearch'] | length > 1 %}
Done.

2021-07-13 09:58 UTC, erzetpe commented on docs/home/howto/DATABASES.md
> +configuration for Open Distro is not supported.
Done.

2021-07-13 10:06 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/opendistro_for_elasticsearch/templates/elasticsearch.yml.j2
> +
Done.

2021-07-13 10:18 UTC, plirglo submitted a review, later dismissed

2021-07-13 11:17 UTC, to-bar approved these changes

2021-07-13 11:32 UTC, plirglo approved these changes

2021-07-13 11:34 UTC, seriva approved these changes

2021-07-13 11:44 UTC, merged