Keycloak
epiphany-platform/epiphany pull request #2429
Opened 2021-07-14 06:32 UTC by rafzei

2021-07-14 12:04 UTC, atsikham approved these changes, later dismissed

2021-07-15 12:50 UTC, plirglo requested changes

2021-07-15 12:50 UTC, plirglo commented on docs/home/howto/KUBERNETES.md
> +All of them has [default configuration](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/defaults/configuration/applications.yml). The common parameters are: nam
```suggestion
All of them have [default configuration](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicli/data/common/defaults/configuration/applications.yml). The common parameters are: name, enabled, namespace, image_path and use_local_image_registry.  
```

2021-07-15 13:01 UTC, plirglo approved these changes

2021-07-15 13:03 UTC, atsikham approved these changes
LGTM

2021-07-15 13:06 UTC, merged