Upgrade PostgreSQL
epiphany-platform/epiphany pull request #2458
Opened 2021-07-22 13:03 UTC by atsikham

2021-07-23 15:00 UTC, to-bar requested changes

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/cli/engine/ansible/AnsibleVarsGenerator.py
> +            # For upgrade we always need common, repository, image_registry, node_exporter and postgresql.
Please add explanation comment

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/cli/epicli.py
> +        if not query_yes_no('Has backup been done?', default='no'):
Please test with `--auto-approve` since we need a possibility to continue for automation

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/extensions/replication/extension.yml
> +    node_id: "{{ pg_node_id }}"
We would like to use underscore for task vars to avoid "conflict" with vars with higher precedence - like `set_fact`. 
```
    _node_id: "{{ pg_node_id }}"
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/pgaudit/packages.yml
> +  when: ansible_facts.packages[old_version.pgaudit.package_name[ansible_os_family]] is defined
I'm not sure if this condition is 100% safe so we may use values from manifest.yml.

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/pgaudit/packages.yml
> +- name: PostgreSQL | Extensions | PgAudit | Install new package(s) for PostgreSQL {{ new_version.pg.version }}
```suggestion
- name: PostgreSQL | Extensions | PgAudit | Install package(s) for PostgreSQL {{ new_version.pg.version }}
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/packages.yml
> +- name: PostgreSQL | Extensions | repmgr | Install new package(s) for PostgreSQL {{ new_version.pg.version }}
```suggestion
- name: PostgreSQL | Extensions | repmgr | Install package(s) for PostgreSQL {{ new_version.pg.version }}
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-checkpoint-location.yml
> +  run_once: true
TODO: Check if we need to add `delegate_facts: true`.

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-checkpoint-location.yml
> +---
Please rename the filename eg. to `repmgr-assert-checkpoint-location.yml`

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-checkpoint-location.yml
> +    that: hostvars[inventory_hostname]['pg_checkpoint'].stdout == pg_checkpoint.stdout
To be corrected

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-conf.yml
> +    node_id: "{{ pg_node_id.stdout }}"
Same as before, new naming convention for task vars

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-register-primary.yml
> +# Done so as after an upgrade there is no possibility to log in
We should consider forcing user to provide config file with current passwords to not overwrite them with old/default ones. Ideally the assertion would be in `preflight` role if possible because I'm not sure if re-apply after upgrade is working for all supported branches.

**Done**: Second thing is to consider adding `run_once` parameter.

**Done**: Also pgpass file should be upgraded.

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-register-standby.yml
> +- name: PostgreSQL | Start and enable new PostgreSQL service
Please replace new word with PG version

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-register-standby.yml
> +- name: PostgreSQL | Start and enable new PostgreSQL service
This task can be split for precise state output

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-old/repmgr-upgrade.yml
>            extensions:
TODO: We need to sync with PR to develop to fix issue

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +#   * new PostgreSQL version is installed
We can do the same approach as for repmgr

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    file: vars/main.yml
For upgrade mode we want to have only named includes

For passing specification to templates we can use _specification with ternary if needed + combine (with recursive)

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +- name: PostgreSQL | Get primary node
Add check about repmgr cluster state (to be healthy - `repmgr cluster show` should return 0) before starting upgrade - in this role or preflight if possible.

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +  failed_when: pg_node_primary_found.rc != 0 or pg_node_primary_found.stdout == ""
```suggestion
  # when there is two primaries (after failover) rc is non-zero
  failed_when: pg_node_primary_found.rc != 0 or pg_node_primary_found.stdout == ""
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    # Ubuntu: automatically creates 'main' cluster and starts postgresql services
🥇

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +            - postgresql-common
Let's try to have defined version (avoid latest)

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    - name: PostgreSQL | RedHat | Ensure that new data directory has correct permissions
Check if task name is correct, it looks like can run on Ubuntu as well

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +      include_tasks: roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-checkpoint-location.yml
Will need to rename this file

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    # TODO: check if we should copy other files from pg.config_dir (such as pg_ctl.conf or pg_ident.conf)
Decided to handle only templated files

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +        # there is a preflight check to confirm that available disk space is enough
:bowtie:

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +                  --jobs {{ ansible_processor_vcpus }}
:star:

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +                      If pg_upgrade generated any .sql files, run them
```suggestion
                      Check {{ pg_upgrade_log_file }} on host {{ pg_primary_node }} for upgrade results.
                      If pg_upgrade generated any .sql files, run them.
                      For more information, refer to PostgreSQL docs (`Post-upgrade processing` section): https://www.postgresql.org/docs/13/pgupgrade.html
```
Add

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    - name: PostgreSQL | Mask old PostgreSQL service
We can test if this is needed for PG13, for PG 10 masking is not required

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    - name: PostgreSQL | Rollback | Remove OS-specific packages
```suggestion
    - name: PostgreSQL | Rollback | Remove PG {{ new_version.pg.version }} related packages
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +          masked: false
Masking is probably not needed

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +      debug:
```suggestion
      fail:
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +      failed_when: true
```suggestion
```

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/preflight/tasks/upgrade.yml
> +            df {{ pg_new.pg.base_dir[ansible_os_family] }} \
Check if df command requires additional flag to follow symlinks

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +        shell: "{{ repmgr.bin_dir[ansible_os_family] }}/repmgr -f {{ repmgr.config_dir[ansible_os_family] }}/repmgr.conf
Please check if we need -f flag here

2021-07-23 15:00 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/upgrade.yml
> +  tasks:
How about having single play, something like:
```
- hosts: postgresql
  become: true
  become_method: sudo
  tasks:
    # repmgr
    - include_role:
        name: postgresql
        tasks_from: upgrade/extensions/replication/pg-old/repmgr-main
      when: "'postgresql' in upgrade_components or upgrade_components|length == 0"

    # postgresql
    - include_role:
        name: postgresql
        tasks_from: upgrade/main
      when: "'postgresql' in upgrade_components or upgrade_components|length == 0"
```

2021-07-23 15:00 UTC, to-bar commented on docs/home/HOWTO.md
> +  - [How to add/remove additional users to/from OS](./howto/SECURITY.md#how-to-add/remove-additional-users-to/from-OS)
TODO: In my case (FF) the links with slashes don't work

2021-07-23 15:00 UTC, to-bar commented on docs/home/howto/PREREQUISITES.md
> +To prevent installation failure of PostgreSQL server it's validated in preflight mode if previous
To be checked if this part can be removed since it looks like it refers to unsupported `epicli` version. @erzetpe should know details.

2021-07-23 15:03 UTC, to-bar commented
I've not reviewed the UPGRADE.md yet.

2021-07-26 06:20 UTC, atsikham commented on core/src/epicli/cli/epicli.py
> +        if not query_yes_no('Has backup been done?', default='no'):
tested

2021-07-26 09:14 UTC, atsikham commented on docs/home/HOWTO.md
> +  - [How to add/remove additional users to/from OS](./howto/SECURITY.md#how-to-add/remove-additional-users-to/from-OS)
I checked it in my branch and it works. Let's take a look at this point together.

2021-07-26 09:14 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +    - name: PostgreSQL | Mask old PostgreSQL service
Done the same as for PG 10.

2021-07-26 10:40 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +- name: PostgreSQL | Get primary node
Added to preflight

2021-07-26 11:01 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/preflight/tasks/upgrade.yml
> +            df {{ pg_new.pg.base_dir[ansible_os_family] }} \
Checked that with symlinks target fs is correctly identified:

```
[root@ec2-34-245-150-1 ec2-user]# ln -s /run/test /
bin/   boot/  data/  dev/   etc/   home/  lib/   lib64/ media/ mnt/   opt/   proc/  root/  run/   sbin/  srv/   sys/   tmp/   usr/   var/   
[root@xxx ec2-user]# ln -s /run/test /opt/
[root@xxx ec2-user]# df
Filesystem     1K-blocks    Used Available Use% Mounted on
devtmpfs          469384       0    469384   0% /dev
tmpfs             492956      16    492940   1% /dev/shm
tmpfs             492956   49744    443212  11% /run
tmpfs             492956       0    492956   0% /sys/fs/cgroup
/dev/nvme0n1p2  31444972 2558084  28886888   9% /
tmpfs              98592       0     98592   0% /run/user/1000
[root@xxx ec2-user]# ls -lah /opt/
total 0
drwxr-xr-x.  4 root root               75 Jul 26 10:58 .
dr-xr-xr-x. 18 root root              236 Feb 25  2020 ..
drwxr-xr-x.  2 root node_exporter      56 Jul 21 22:46 node_exporter
drwxr-xr-x.  2 root postgres_exporter  66 Jul 21 22:49 postgres_exporter
lrwxrwxrwx.  1 root root                9 Jul 26 10:58 test_dir_rootfs -> /run/test
[root@xxx ec2-user]# df /opt/test_dir_rootfs/
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs             492956 49744    443212  11% /run
```

2021-07-26 12:43 UTC, erzetpe approved these changes, later dismissed

2021-07-26 12:43 UTC, erzetpe commented on docs/home/howto/PREREQUISITES.md
> +To prevent installation failure of PostgreSQL server it's validated in preflight mode if previous
This should only concern upgrade from PosgtgreSQL 9.5 installed from Software Collections, but this is something from the ancient times. :)

2021-07-26 13:19 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +        shell: "{{ repmgr.bin_dir[ansible_os_family] }}/repmgr -f {{ repmgr.config_dir[ansible_os_family] }}/repmgr.conf
We don't need this when there is a symlink to a default configuration, but as we still support PostgreSQL 10, I think we should leave that as it is.

2021-07-26 13:36 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +            - postgresql-common
TODO: discuss

2021-07-27 12:29 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-checkpoint-location.yml
> +  run_once: true
This file was removed

2021-07-27 13:33 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-register-primary.yml
> +# Done so as after an upgrade there is no possibility to log in
Will be added in documentation

2021-07-27 13:34 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> +            - postgresql-common
There is no sense for that as package version is not related somehow to postgres version. Decided to keep current approach.

2021-07-27 13:56 UTC, atsikham commented on docs/home/HOWTO.md
> +  - [How to add/remove additional users to/from OS](./howto/SECURITY.md#how-to-add/remove-additional-users-to/from-OS)
Fixed

2021-07-28 09:36 UTC, closed without merging

2021-07-28 09:36 UTC, atsikham commented
New PR #2468 was created