Feature/upgrade pgbouncer and pgpool
epiphany-platform/epiphany pull request #2462
Opened 2021-07-23 10:52 UTC by plirglo

## Upgrade pgpool to v4.2.3 and pgbouncer to v1.15
## Currently HA with pgpool and pgbouncer works only with md5 passwords - support for scram sha-256 needs to be added.

## Postgres
- Added configurable MD5 or SHA-256 password usage for PostgreSQL
- modified core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/main.yml file to check for primary node before starting pgpool configuration (Fix for #1702) 

## PgPool:
- Configuration with pgpool version 4.2.3 (upgraded)
- libpgpool.sh scipt is mostly developed by Bitnami, i've only added steps to create SHA-256 password encryption for epi_pgpool_postgres_admin - original file is located [here](https://github.com/bitnami/bitnami-docker-pgpool/blob/4.2.3-debian-10-r46/4/debian-10/rootfs/opt/bitnami/scripts/libpgpool.sh)
- some other modifications in init scripts required by newer version of pgpool
- minor required changes in pgpool.conf file

## PgBouncer:
- Configuration with pgbouncer version 1.15 (upgraded / switched to [Bitnami image](https://github.com/bitnami/bitnami-docker-pgbouncer))
- libpgbouncer.sh scipt is developed by Bitnami, i've removed only some chcecks which are not necessary since we mount config file from configmap - original [script](https://github.com/bitnami/bitnami-docker-pgbouncer/tree/master/1/debian-10/rootfs/opt/bitnami/scripts)
- Added pgbouncer.ini to configmap

2021-07-28 09:44 UTC, atsikham commented
Target branch `feature/upgrade-postgresql` was replaced by `feature/upgrade-postgresql-13`, please change that for this PR.

2021-08-09 11:56 UTC, erzetpe requested changes

2021-08-09 11:56 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/applications/templates/pgpool/04-deployment.yml.j2
> +            - name: pgpool-config-files
Please change the name of the key to not duplicate.

2021-08-09 11:56 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/applications/templates/pgpool/04-deployment.yml.j2
> +            - name: pgpool-init-scripts
Please change the name of the key to not duplicate.

2021-08-09 11:56 UTC, erzetpe commented on core/src/epicli/data/common/ansible/playbooks/roles/applications/templates/pgpool/04-deployment.yml.j2
> +            - name: pgpool-config-dir
Please change the name of the key to not duplicate.

2021-08-09 12:27 UTC, erzetpe approved these changes, later dismissed

2021-08-10 04:39 UTC, rafzei submitted a review, later dismissed
Just for your info: 
I see there are already the newest versions:
[Pgpool 4.2.4](https://github.com/pgpool/pgpool2/compare/V4_2_3...V4_2_4)
[Bitnami link](https://hub.docker.com/r/bitnami/pgpool/tags?page=1&ordering=last_updated)
[PGbouncer](https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_16_0)
[Bitnami link](https://hub.docker.com/r/bitnami/pgbouncer/tags?page=1&ordering=last_updated)
There is also one fix in [md5 context](https://github.com/pgbouncer/pgbouncer/commit/435d737fd4696d33100d68c6852669a2961eb7bd)

2021-08-10 06:11 UTC, erzetpe approved these changes

2021-08-10 06:27 UTC, plirglo commented
> Just for your info:
> I see there are already the newest versions:
> [Pgpool 4.2.4](https://github.com/pgpool/pgpool2/compare/V4_2_3...V4_2_4)
> [Bitnami link](https://hub.docker.com/r/bitnami/pgpool/tags?page=1&ordering=last_updated)
> [PGbouncer](https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_16_0)
> [Bitnami link](https://hub.docker.com/r/bitnami/pgbouncer/tags?page=1&ordering=last_updated)
> There is also one fix in [md5 context](https://github.com/pgbouncer/pgbouncer/commit/435d737fd4696d33100d68c6852669a2961eb7bd)

Thanks, we don't use md5 encryption with plain-text passwords, so i think this should not impact our configuration

2021-08-10 06:38 UTC, rafzei approved these changes

2021-08-10 06:40 UTC, merged

2021-08-10 06:45 UTC, plirglo commented
Applies also to task #2076