[Upgrade] PostgreSQL 13
epiphany-platform/epiphany pull request #2468
Opened 2021-07-28 08:25 UTC by atsikham

Postgresql 13 + PgAudit upgrade part

Original PR to check conversations: #2458 

TODO:
* UPGRADE.md review
* Sync with #2459

2021-07-29 13:20 UTC, erzetpe approved these changes, later dismissed

2021-07-29 17:21 UTC, to-bar requested changes

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +          | awk 'NR==1{for (i=1; i<=NF; i++) if (tolower($i) == "filesystem" ){dev=i; break}} NR==2{print $dev}'
```suggestion
        df --output=source {{ pg_new.pg.base_dir[ansible_os_family] }} | tail -1
```

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +  command: "{{ pg_old.repmgr.bin_dir[ansible_os_family] }}/repmgr cluster show --csv"
Please add `-f` flag here to be on the safe side since symlink to config file for Ubuntu has been added in v0.7 but repmgr in v0.6 and this is our first repmgr upgrade

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/extensions/replication/extension.yml
> +    _pg_node_primary: "{{ groups.postgresql[0] }}" # the first node in the group is primary
```suggestion
    _pg_primary_node: "{{ groups.postgresql[0] }}" # the first node in the group is primary
```

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/extensions/replication/extension.yml
> +      when: _pg_node_primary == inventory_hostname
```suggestion
      when: _pg_primary_node == inventory_hostname
```

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/extensions/replication/extension.yml
> +      when: _pg_node_primary != inventory_hostname
```suggestion
      when: _pg_primary_node != inventory_hostname
```

2021-07-29 17:21 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/repmgr-register-standby.yml
> +    name: "{{ pg.service_name[ansible_os_family] }}"
How about waiting for the instantiated service on Ubuntu to be started?

Something like:
```
- name: Ensure PostgreSQL instantiated service is running
  systemd:
    name: "{{ pg.instantiated_service_name[ansible_os_family] }}"
    state: started
  when: pg.instantiated_service_name[ansible_os_family] != None
```

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +  failed_when: pg_node_primary_found.rc != 0 or pg_node_primary_found.stdout == ""
```suggestion
  register: pg_primary_node_found
  # when there are two primary nodes (after failover) rc is non-zero
  failed_when: pg_primary_node_found.rc != 0 or pg_primary_node_found.stdout == ""
```

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +  delegate_to: "{{ groups.postgresql[0] }}"
Do we need this line? On healthy cluster `repmgr cluster show` gives the same result on all nodes and `run_once` executes this task on the first host in the current batch (normally it will be `groups.postgresql[0]`). If you want to keep this line for explicitness, please add a comment that there is no requirement to run this command on primary node.

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    pg_primary_node: "{{ pg_primary_found.stdout | default (groups.postgresql[0]) }}"
```suggestion
    pg_primary_node: "{{ pg_primary_node_found.stdout | default('') }}"
```

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    - name: PostgreSQL | Extensions | PgAudit | Include pakage(s) installation tasks
```suggestion
    - name: PostgreSQL | Extensions | PgAudit | Include package(s) installation tasks
```

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    - name: PostgreSQL | Extensions | repmgr | Include pakage(s) installation tasks
```suggestion
    - name: PostgreSQL | Extensions | repmgr | Include package(s) installation tasks
```

2021-07-30 10:19 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    - name: PostgreSQL | Extensions | repmgr | Update pgpass file
Please add when condition for replication

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +                  enabled: "{{ manifest.specification.extensions.pgaudit.enabled }}"
```suggestion
                  enabled: "{{ pg_is_pgaudit_used }}"
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +                  enabled: "{{ manifest.specification.extensions.replication.enabled }}"
```suggestion
                  enabled: "{{ pg_is_repmgr_used }}"
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    - name: PostgreSQL | Stop PostgreSQL services on standby nodes
```suggestion
    - name: PostgreSQL | Stop PostgreSQL services on primary node
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +    - name: PostgreSQL | Stop PostgreSQL services on primary node
```suggestion
    - name: PostgreSQL | Stop PostgreSQL services on standby node
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +                      Check {{ _pg_upgrade_log_file }} on host {{ pg_primary_node }} for upgrade results.
```suggestion
                      Check {{ _pg_upgrade_log_file }} on host {{ inventory_hostname }} for upgrade results.
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +        - name: PostgreSQL | Start PostgreSQL {{ new_version.pg.version }} service
We may need to ensure instantiated service started, like:

```
- name: PostgreSQL | Debian | Ensure that instantiated PostgreSQL {{ new_version.pg.version }} service started
  when: ansible_os_family == 'Debian'
  systemd:
    name: "{{ new_version.pg.instantiated_service_name.Debian }}"
    state: started
```

2021-07-30 12:36 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/requirements.x86_64.txt
> +repmgr10-5.2.1 # used to upgrade only repmgr
```suggestion
repmgr10-5.2.1 # used to upgrade repmgr first
```

2021-07-30 13:51 UTC, to-bar requested changes

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +- If you run upgrade from version older than 0.8 you should make sure that you've got enough disk space on master (which
```suggestion
- If you need to upgrade a cluster deployed with `epicli` in version earlier than 0.8, you should make sure that you've got enough disk space on master (which
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +  os disks on master machine according to cloud provider
```suggestion
  OS disk on master machine according to cloud provider
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +  32 GB disk which is not enough to properly upgrade cluster (we recommend 50 GB). Before you run upgrade please extend
```suggestion
  32 GB disk which is not enough to properly upgrade cluster (we recommend at least 64 GB). Before you run upgrade, please extend
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +  Azure size (2 CPUs, 7 GB RAM) machine, or it's equivalent on AWS and on-prem installations. It's very related to
```suggestion
  Azure size (2 CPUs, 7 GB RAM) machine, or its equivalent on AWS and on-prem installations. It's very related to
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +   which each other:
```suggestion
   with each other:
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +To run Epicli check the [Prerequisites](./PREREQUISITES.md)
```suggestion
Before running `epicli`, check the [Prerequisites](./PREREQUISITES.md)
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +2. The scripts in the `prepare_scripts` will be used to download all requirements. To do that copy the `prepare_scripts`
```suggestion
2. The scripts in the `prepare_scripts` will be used to download all requirements. To do that, copy the `prepare_scripts`
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +will result in the following error while its draining a these pods during an upgrade:
```suggestion
will result in the following error while draining pods during an upgrade:
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +Upgrade procedure is based on an [PostgreSQL documentation](https://www.postgresql.org/docs/13/pgupgrade.html) and
```suggestion
Upgrade procedure is based on [PostgreSQL documentation](https://www.postgresql.org/docs/13/pgupgrade.html) and
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +  by [wal_keep_size](https://www.postgresql.org/docs/13/runtime-config-replication.html#GUC-WAL-KEEP-SIZE) with a
```suggestion
  by [wal_keep_size](https://www.postgresql.org/docs/13/runtime-config-replication.html#GUC-WAL-KEEP-SIZE) with the
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +  but changes to `archive_mode` require a full PostgreSQL server restart, while archive_command changes can be applied
```suggestion
  but changes to `archive_mode` require a full PostgreSQL server restart, while `archive_command` changes can be applied
```

2021-07-30 13:51 UTC, to-bar commented on docs/home/howto/UPGRADE.md
> +please check logs after an upgrade to see if additional steps required.
```suggestion
please check logs after the upgrade to see if additional steps are required.
```

2021-07-30 14:40 UTC, to-bar approved these changes

2021-08-02 05:59 UTC, erzetpe approved these changes

2021-08-02 06:30 UTC, merged