Minor fixes for validation.
epiphany-platform/epiphany pull request #2474
Opened 2021-07-29 11:56 UTC by seriva

- Added fix for input document validation
- Note for breaking changes: yes|no need to be true|false only now.

2021-07-29 11:59 UTC, erzetpe approved these changes, later dismissed

2021-07-29 11:59 UTC, przemyslavic commented
/azp run

2021-07-29 12:17 UTC, atsikham submitted a review, later dismissed

2021-07-29 16:49 UTC, to-bar requested changes

2021-07-29 16:49 UTC, to-bar commented on core/src/epicli/cli/helpers/objdict_helpers.py
> +                if val == 'no':
```suggestion
                elif val == 'no':             
```

2021-07-29 18:40 UTC, przemyslavic commented
/azp run

2021-07-29 19:01 UTC, przemyslavic commented
❤️

2021-07-30 05:58 UTC, seriva commented on core/src/epicli/cli/helpers/objdict_helpers.py
> +                if val == 'no':
Fixed.

2021-07-30 07:06 UTC, przemyslavic approved these changes

2021-07-30 07:17 UTC, przemyslavic commented
/azp run

2021-07-30 07:42 UTC, to-bar approved these changes

2021-07-30 08:02 UTC, merged