Add Internet connection test to download-requirements.sh (2124)
epiphany-platform/epiphany pull request #2493
Opened 2021-08-06 14:06 UTC by sbbroot

2021-08-09 11:59 UTC, erzetpe submitted a review, later dismissed

2021-08-10 04:02 UTC, rafzei reviewed
Hmm.. I think we shouldn't even do this task before #805.
Anyways since it's already there @sbbroot please use [shellcheck extension for vscode](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck). I see a bunch of underscores in your code. Please check them :v:

2021-08-10 04:02 UTC, rafzei commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# TODO crane
How about Crane? If we are going to use simple wget <URL> checking I would remove this section.

2021-08-10 04:02 UTC, rafzei commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +readonly CONNECTION_CHECK_ENABLED="yes"
I personally like lowercase variables in the case of one shell scope.

2021-08-10 04:02 UTC, rafzei commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +__check_wget() {
Do we need __ prefix?

2021-08-10 04:02 UTC, rafzei commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +        check_connection wget $file_url
Pay attention to indentation - you have used space instead of tab in this particular line. I see for this doc is set "Tab Size: 4"

2021-08-10 04:02 UTC, rafzei commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +check_connection() {
I would add echo with a message at the beginning of this function

2021-08-13 13:06 UTC, to-bar requested changes

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +readonly CONNECTION_CHECK_ENABLED="yes"
I would use more explicit (narrower) name, e.g. `internet_access_checks_enabled`

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +check_connection yum
The function is called just bellow the `--- Backup yum repositories ---` section (comment) but it tests connectivity what is not related to the backup. Please move it above the `=== Packages ===` section.

IMO, it would be nice to add new section, for example:
```
# --- Run internet access tests ---
check_connection yum
check_connection wget $first_url $second_url
```
For `$first_url` and `$second_url` we need any valid URLs (theoretically available files from two different domains) just to test if wget works (behind a proxy it may require extra settings in /etc/wgetrc or environment variables, such as `https_proxy`).
Why 2 URLs? The test should fail only if both files are not available since it's more likely that a single file may be not available (temporarily) on the remote server than two. When a file is not available, it doesn't necessarily mean a problem on the client side, thus I would suggest the double checking to avoid false/misleading results.

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +        check_connection wget $file_url
I would like to run all connection tests as prerequisites (close to the beginning, under the `--- Checks ---` section) in order to fail early if not met (to save time).

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# param $1: url which will be tested
```suggestion
# param $1: url to be tested
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# param $@: args which will be printed
```suggestion
# param $@: args to be printed
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    [[ $# -lt 1 ]] && exit_with_error "(curl), no url provided"
```suggestion
    (( $# > 0 )) || exit_with_error "__check_curl: no url provided"
```
IMO having real function name would be more informative.

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    echol "Testing connection to: ($url) using: (curl)..."
```suggestion
    echol "Testing connection to \"${url}\" using curl..."
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    err_msg=$(curl -S --silent $url 2>&1 >/dev/null) || exit_with_error "(curl) failed, reason: ($err_msg)"
```suggestion
    err_msg=$(curl --show-error --silent $url 2>&1 >/dev/null) || exit_with_error "curl failed, reason: ($err_msg)"
```
IMO in scripts it's better to use options in long form unless they are commonly known (intuitive/popular).

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# param $1: url which will be tested
```suggestion
# param $1: url to be tested
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    [[ $# -lt 1 ]] && exit_with_error "(wget), no url provided"
```suggestion
    (( $# > 0 )) || exit_with_error "__check_wget: no url provided"
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +__check_wget() {
I guess this is to mark function as "private"/internal/helper - not called in external file.

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    echol "Testing connection to: ($url) using: (wget)..."
```suggestion
    echol "Testing connection to \"${url}\" using wget..."
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    err_msg=$(wget --spider -nd $url 2>&1 >/dev/null) || exit_with_error "(wget) failed, reason: ($err_msg)"
```suggestion
    err_msg=$(wget --spider --no-directories $url 2>&1 >/dev/null) || exit_with_error "wget failed, reason: ($err_msg)"
```
Do we need `--no-directories` option assuming that we will use only links to a single file?

I would prefer to return test result instead of exiting. In old Bash (as in RHEL 7) returning array is very limited but we could for example print array like: `printf '%s\n' "${array[@]}"` and have exit code in the first line - 0 - tests passed, 1 - failed. If failed, then have in next lines error message. Such approach would allow to run all tests in parent function then interpret results, for example print "report"/summary for all tools.

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# Use `apt update` to make sure that there is connection to repositories.
It looks like testing all repositories. IMO we may need to test repos one by one (in a loop) and finish testing (exit from the loop) on the first succeeded. I'm not sure about exit code when at least one repo is not available - but it looks like we may get false result using this command. We need to test whether **any** single repo is available instead of **all** of them.
This link may be helpful: https://askubuntu.com/questions/65245/apt-get-update-only-for-a-specific-repository

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    echol "Testing (apt) connection..."
```suggestion
    echol "Testing apt connection..."
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    [[ $UID -ne 0 ]] && exit_with_error "(apt) needs to be run as a root"
```suggestion
    (( $UID == 0 )) || exit_with_error "apt needs to be run as root"
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    err_msg=$(apt update 2>&1 >/dev/null) || exit_with_error "(apt) failed, reason: ($err_msg)"
```suggestion
    err_msg=$(apt update 2>&1 >/dev/null) || exit_with_error "\"apt update\" failed, reason: ($err_msg)"
```

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# Pick first available repo, clean the cache and then query available packages.
Similar case to apt. Please see my comment there.
Probably we don't need to clean cache for all repos.
I would try something like this (in a loop):
`yum makecache fast --disablerepo="*" --enablerepo=<repo>`

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# param $1: url which will be tested
```suggestion
# param $1: repo/image to be tested
```
`repo` **or** `image` should be chosen depending on crane command (`crane ls` vs `crane pull`). I guess `crane ls` can be faster.

2021-08-13 13:06 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# TODO crane
@rafzei This check is to test `crane` (`crane ls` or `crane pull`), not `wget`.
Someone may need extra setup behind a proxy: https://github.com/google/go-containerregistry/issues/861

2021-08-18 12:54 UTC, sbbroot commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +check_connection() {
All of those functions have proper echo messages, I'm not sure if another one is needed.

2021-08-18 12:55 UTC, sbbroot commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +# param $1: url which will be tested
Crane ls will be used.

2021-08-20 17:32 UTC, to-bar commented
How about not exiting in a child function but in the parent? For example:

```
__check_curl() {
    (( $# > 0 )) || exit_with_error "__check_curl: no url provided"
    local url=$1

    echol "Testing connection to: \"${url}\" using curl..."

    err_msg=$(curl --show-error --silent "$url" 2>&1 >/dev/null); rc=$?
    if (( rc > 0)); then
        echol "curl failed, reason: [$err_msg], exit code: $rc"
        return $rc
    fi
}

check_connection() {
    if ${tools[$tool]} $@; then
        echol "PASSED"
    else
        # here we can decide what to do, e.g. run `exit_with_error` or return exit code from child function
        echol "FAILED"
    fi
}

check_connection curl https://github.fake
check_connection curl https://github.com

# output:

Testing connection to: "https://github.fake" using curl...
curl failed, reason: [curl: (6) Could not resolve host: github.fake], exit code: 6
FAILED
Testing connection to: "https://github.com" using curl...
PASSED
```

2021-08-30 08:09 UTC, erzetpe approved these changes, later dismissed

2021-08-31 12:27 UTC, to-bar requested changes

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/centos-7/download-requirements.sh
> +check_connection yum $(yum repolist --quiet | tail -n +2 | cut -d' ' -f1 | cut -d'/' -f1 | sed 's/!//')
```suggestion
check_connection yum $(yum repolist --quiet | tail -n +2 | cut -d' ' -f1 | cut -d'/' -f1 | sed 's/^!//')
```
yum repolist output's first column as ! if the repository has expired metadata.

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +        if (( $? != 0 )); then
How about return on the first success to save time?

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    [[ $# -lt 1 ]] && exit_with_error "(tool) argument not provided"
```suggestion
    [[ $# -lt 1 ]] && exit_with_error '"tool" argument not provided'
```

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +    [[ ! -n ${tools[$tool]} ]] && exit_with_error "no such tool ($tool)"
```suggestion
    [[ ! -n ${tools[$tool]} ]] && exit_with_error "no such tool: \"$tool\""
```

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/common/common_functions.sh
> +            exit_with_error "Connection failure, reason: ($last_error)"
```suggestion
            exit_with_error "Connection failure, reason: [$last_error]"
```
() are probably used more often than [] in error message. 
IMO `[curl: (6) Could not resolve host: google.com; Name or service not known]` looks better than `(curl: (6) Could not resolve host: google.com; Name or service not known)`

2021-08-31 12:27 UTC, to-bar commented on core/src/epicli/data/common/ansible/playbooks/roles/repository/files/download-requirements/redhat-7/download-requirements.sh
> +check_connection yum $(yum repolist --quiet | tail -n +2 | cut -d' ' -f1 | cut -d'/' -f1 | sed 's/!//')
```suggestion
check_connection yum $(yum repolist --quiet | tail -n +2 | cut -d' ' -f1 | cut -d'/' -f1 | sed 's/^!//')
```

2021-08-31 16:16 UTC, to-bar submitted a review, later dismissed

2021-08-31 16:31 UTC, to-bar approved these changes

2021-09-01 06:27 UTC, erzetpe approved these changes

2021-09-01 06:35 UTC, merged