Introduced a _merge_mode parameter for merging list
epiphany-platform/epiphany pull request #2504
Opened 2021-08-24 18:13 UTC by seriva

Introduced a _merge_mode parameter for merging list based on the comments [here](https://github.com/epiphany-platform/epiphany/issues/1294#issuecomment-900194372)

In short this allows for adding a directive on how named list should be processed, or **merge** or **overwrite**, where **overwrite** is the default when nothing is defined. For example:

```yaml
kind: configuration/applications
title: "Kubernetes Applications Config"
name: default
provider: azure
specification:
  applications:
  - _merge_mode: 'merge'
  - name: auth-service # requires PostgreSQL to be installed in cluster
    enabled: true
```

2021-08-26 12:53 UTC, to-bar requested changes

2021-08-26 12:53 UTC, to-bar commented on docs/home/HOWTO.md
> +- [Schema](./howto/SCHEMA.md)
IMO `Schema` may be too generic. It's rather related to validations. How about `Configuration file` or something like that?
And `Elasticsearch` below looks like a mistake 😉

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +## Schema
```suggestion
## Inheritance
```

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +## Schema
We could add info similar to [this one](https://docs.rubocop.org/rubocop/configuration.html#inheritance) - unless we already have in another doc.

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +Epiphany uses a concept called **named lists** in the configuration YAML. Every entry in a **named lists**  list will have a ```name``` field to identify it and make it unique for merge operations:
```suggestion
Epiphany uses a concept called **named lists** in the configuration YAML. Every item in a **named list**  has the ```name``` key to identify it and make it unique for merge operation:
```

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +    property2: property2
```suggestion
  - name: item1
    property1: value1
    property2: value2
  - name: item2
    property1: value3
    property2: value4
```

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +By default, a **named list** inside your configuration it will completely overwrite the defaults that Epiphany provides. This behaviour is on purpose so when you, for example, define a list of users
```suggestion
By default, a **named list** in your configuration file will completely overwrite the defaults that Epiphany provides. This behaviour is on purpose so when you, for example, define a list of users for Kafka inside your configuration it completely overwrites the users defined in the [Kafka defaults](https://github.com/epiphany-platform/epiphany/blob/9ff9bb266cd6addf309059a8a5e7a48835daafc3/core/src/epicli/data/common/defaults/configuration/kafka.yml#L34).
```

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +In some cases however you don't want to overwrite a **named list**. A good example would be the [application configurations.](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicl
```suggestion
In some cases, however, you don't want to overwrite a **named list**. A good example would be the [application configurations](https://github.com/epiphany-platform/epiphany/blob/v1.0.1/core/src/epicli/data/common/defaults/configuration/applications.yml).
```
IMO it's better to avoid linking to develop branch since things are changing there 😉

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +You don't want to re-define every entry just to make sure Epiphany has all default entries needed by the Ansible automation. That is where the ```_merge``` metadata tag comes in. It will let you defi
```suggestion
You don't want to re-define every item just to make sure Epiphany has all default items needed by the Ansible automation. That is where the ```_merge``` metadata tag comes in. It will let you define whether you want to ```overwrite``` or ```merge``` a **named list** by setting it to ```true``` or ```false```.
```

2021-08-26 12:53 UTC, to-bar commented on docs/home/howto/SCHEMA.md
> +The ```_merge``` entry with ```true``` will tell Epicli to merge the application list and only change the ```enabled: true``` entry inside the ```auth-service``` and take the rests of the [configurat
```suggestion
The ```_merge``` item with ```true``` will tell epicli to merge the application list and only change the ```enabled: true``` setting inside the ```auth-service``` and take the rests of the [configuration/applications]((https://github.com/epiphany-platform/epiphany/blob/v1.0.1/core/src/epicli/data/common/defaults/configuration/applications.yml)) configuration from the defaults.
```

2021-08-26 13:34 UTC, seriva commented on docs/home/howto/SCHEMA.md
> +In some cases however you don't want to overwrite a **named list**. A good example would be the [application configurations.](https://github.com/epiphany-platform/epiphany/blob/develop/core/src/epicl
Good point

2021-08-26 13:51 UTC, seriva commented on docs/home/HOWTO.md
> +- [Schema](./howto/SCHEMA.md)
Yeah agreed, Configuration file is better choice.

2021-08-26 13:55 UTC, to-bar submitted a review, later dismissed

2021-08-26 14:25 UTC, erzetpe submitted a review, later dismissed

2021-09-02 14:15 UTC, przemyslavic commented
/azp run

2021-09-02 14:26 UTC, przemyslavic commented
/azp run

2021-09-02 18:06 UTC, rafzei approved these changes, later dismissed

2021-09-03 07:11 UTC, to-bar submitted a review, later dismissed

2021-09-06 14:43 UTC, rafzei approved these changes

2021-09-06 14:45 UTC, przemyslavic commented
/azp run

2021-09-07 07:14 UTC, przemyslavic approved these changes

2021-09-07 07:33 UTC, merged