Add Spike template
epiphany-platform/epiphany pull request #2516
Opened 2021-08-26 12:32 UTC by rafzei

2021-08-26 13:17 UTC, mkyc requested changes

2021-08-26 13:17 UTC, mkyc commented on .github/ISSUE_TEMPLATE/spike.md
> +
Since we found today that we do not understand why something was spiked long time ago, I think we should add here short subsection like "what is a reason or source for this spike". Maybe before "additional context"?

2021-08-26 13:19 UTC, plirglo commented on .github/ISSUE_TEMPLATE/spike.md
> +* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters)
```suggestion
* [ ] The results of the spike are presented in a table (to show simply what are compared or researched parameters) / not applicable
```

2021-08-27 11:05 UTC, mkyc approved these changes
🎉

2021-08-27 15:06 UTC, seriva approved these changes

2021-08-29 16:17 UTC, merged