Add more retries for running ansible ping command (#2271)
epiphany-platform/epiphany pull request #2557
Opened 2021-09-08 07:10 UTC by sbbroot

* Add optional epicli argument `ping-retries` for apply and upgrade

2021-09-08 08:38 UTC, seriva approved these changes

2021-09-08 08:38 UTC, seriva commented on core/src/epicli/cli/engine/ApplyEngine.py
> +        self.__ping_retries: int = input_data.ping_retries
Apply __ everywhere if ur bored;)

2021-09-08 11:18 UTC, erzetpe approved these changes

2021-09-08 11:21 UTC, erzetpe requested changes
Please change the the branch.

2021-09-09 05:21 UTC, seriva commented
> Please change the the branch.

Yeah Pawo is right, this is not for 1.2 anymore. So put it on a separate branch and move the changelog to a new 1.3 file pls.

2021-09-09 14:08 UTC, to-bar approved these changes, later dismissed

2021-09-09 14:08 UTC, to-bar commented on core/src/epicli/cli/epicli.py
> +    optional.add_argument('--ping-retries', dest='ping_retries', type=int, required=False, action='store', default=5,
IMO it would be nice to have arguments in alphabetic order but this can be done next time.

2021-09-09 14:22 UTC, to-bar commented
> 
> 
> > Please change the the branch.
> 
> Yeah Pawo is right, this is not for 1.2 anymore. So put it on a separate branch and move the changelog to a new 1.3 file pls.

IMO the target branch is ok (`develop`). We will need to create `v1.2` for releasing 1.2.0.  I would opt for keeping this PR open until the new branch is created. However the entry in changelog should be moved to the new file (`CHANGELOG-1.3.md`).

2021-09-10 09:28 UTC, mkyc commented
Confirm with @przemyslavic before merging that he is ok with it.

2021-09-13 06:43 UTC, seriva commented
> Please change the the branch.

As we discussed last week, its a minor change, so if @przemyslavic  is good with it I am good for merging for 1.2.

2021-09-13 06:43 UTC, seriva approved these changes, later dismissed

2021-09-14 11:51 UTC, przemyslavic commented
/azp run

2021-09-14 13:30 UTC, przemyslavic approved these changes

2021-09-14 13:36 UTC, erzetpe approved these changes

2021-09-14 13:58 UTC, merged