Fix epicli apply --full region values (#2497)
epiphany-platform/epiphany pull request #2599
Opened 2021-09-21 05:47 UTC by sbbroot

* Add separate epiphany-cluster.yml for Azure

* Move epiphany-cluster.yml from common to aws

2021-09-21 07:16 UTC, plirglo commented
Please task to changelog.

2021-09-21 08:09 UTC, rafzei submitted a review, later dismissed

2021-09-21 08:19 UTC, rafzei submitted a review, later dismissed

2021-09-21 09:57 UTC, atsikham requested changes
_Point for discussion:_ shouldn't we consider having still a common configuration and merging that with a specific one for each cloud provider?

2021-09-22 06:48 UTC, seriva commented
> _Point for discussion:_ shouldn't we consider having still a common configuration and merging that with a specific one for each cloud provider?

Issue would be that this would require some different processes just for the cluster-config. So after discussion we decided to have dedicated document for each provider as we already have with the minimal cluster config. Only thing I think that is missing is the default config for ```any``` provider.

2021-09-22 06:49 UTC, seriva reviewed
- Does the any provider has a dedicated document?
- Did you check if their where any changes needed in merging code when doing apply etc?

2021-09-22 09:50 UTC, seriva commented on core/src/epicli/data/any/defaults/epiphany-cluster.yml
> +  cloud:
Cloud can be removed.

2021-09-22 09:53 UTC, seriva commented on core/src/epicli/data/azure/defaults/epiphany-cluster.yml
> +    credentials: # todo change it to get credentials from vault
Cloud is AWS only I think.

2021-09-22 09:54 UTC, seriva commented on core/src/epicli/data/azure/defaults/epiphany-cluster.yml
> +    use_service_principal: False
use_service_principal is Azure only so it can be removed from the AWS config if present.

2021-09-22 09:55 UTC, seriva reviewed
Also make sure that the count for each component are the same across all providers.

2021-09-22 16:06 UTC, seriva commented on core/src/epicli/data/aws/defaults/epiphany-cluster.yml
>      subscription_name: YOUR-SUB-NAME
subscription_name is also for Azure only so can be removed.

2021-09-22 18:38 UTC, seriva submitted a review, later dismissed

2021-09-22 21:38 UTC, atsikham approved these changes, later dismissed

2021-09-23 08:13 UTC, rafzei approved these changes, later dismissed

2021-09-23 13:11 UTC, seriva approved these changes, later dismissed

2021-09-30 08:49 UTC, seriva commented
Merged as per @przemyslavic  permission as we want todo #2643 ASAP. He will test it from develop.

2021-09-30 08:49 UTC, seriva approved these changes

2021-09-30 08:53 UTC, plirglo approved these changes

2021-09-30 08:53 UTC, merged