RabbitMQ monitoring (#1487)
epiphany-platform/epiphany pull request #2603
Opened 2021-09-22 06:48 UTC by sbbroot

* Add Grafana dashboards for RabbitMQ monitoring

2021-09-22 09:11 UTC, atsikham reviewed
Looks good, but conflicts need to be resolved.

2021-09-22 17:59 UTC, rafzei requested changes
Please update table with license for this dashboard, [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/COMPONENTS.md#predefined-grafana-dashboards)

2021-09-22 17:59 UTC, rafzei commented on core/src/epicli/data/common/defaults/configuration/grafana.yml
> +    #   datasource: 'Prometheus'
It's actually useless here (it's just an example)

2021-09-23 06:29 UTC, seriva approved these changes

2021-09-23 07:40 UTC, erzetpe approved these changes

2021-09-23 07:51 UTC, rafzei approved these changes

2021-09-30 08:48 UTC, seriva commented
Merged as per @przemyslavic  permission as we want todo #2643 ASAP. He will test it from develop.

2021-09-30 08:49 UTC, merged