Fix 3 PostgreSQL upgrade issues
epiphany-platform/epiphany pull request #2624
Opened 2021-09-24 13:22 UTC by to-bar

- #2619
- #2622
- #2623

2021-09-24 18:43 UTC, to-bar commented
/azp run

2021-09-27 07:17 UTC, przemyslavic commented
/azp run

2021-09-27 08:45 UTC, atsikham requested changes

2021-09-27 08:45 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +          become: yes
```suggestion
          become: true
```

2021-09-27 08:45 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +          loop: "{{ _services | reject('==', '') }}"
Is `reject` necessary here?

2021-09-27 08:45 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +      block:
Block seems to be unnecessary for one task or the next one can be moved into this block.

2021-09-27 08:45 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +          become: yes
```suggestion
          become: true
```

2021-09-27 12:23 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +          loop: "{{ _services | reject('==', '') }}"
Resolved as it will not make worse.

2021-09-27 12:50 UTC, atsikham commented on core/src/epicli/data/common/ansible/playbooks/roles/postgresql/tasks/upgrade/upgrade.yml
> +          - "{{ new_version.pg.instantiated_service_name[ansible_os_family] }}"
```suggestion
        - name: Rollback | Disable PG {{ new_version.pg.version }} service
          when:
            - ansible_facts.services[service_name + '.service'] is defined
            - service_name != old_version.pg.service_name[ansible_os_family]
          systemd:
            name: "{{ service_name }}"
            enabled: false
            masked: "{{ True if (service_name == new_version.pg.instantiated_service_name[ansible_os_family]) else False }}"
          loop_control:
            loop_var: service_name
          loop: "{{ _services | reject('==', '') }}"
          vars:
            _services:
              - "{{ new_version.pg.service_name[ansible_os_family] }}"
              - "{{ new_version.pg.instantiated_service_name[ansible_os_family] }}"
```

2021-09-27 13:13 UTC, atsikham approved these changes

2021-09-27 13:15 UTC, przemyslavic approved these changes

2021-09-27 13:24 UTC, merged