Documentation for Azure Files and EFS
epiphany-platform/epiphany pull request #2646
Opened 2021-09-30 10:30 UTC by atsikham

Task #1974. It already has been supported but not documented.

2021-09-30 11:17 UTC, seriva commented
This needs changes for sure because of #2645.

2021-09-30 11:21 UTC, seriva commented
First we need to merge #2643.

2021-10-01 10:54 UTC, atsikham commented on data/aws/defaults/infrastructure/efs-storage.yml
> -    populate_sg_rules: true # when set to true, security group for EFS will allow traffic from other clusters, groups
Haven't found places where it's used.

2021-10-01 11:10 UTC, plirglo requested changes

2021-10-01 11:10 UTC, plirglo commented on docs/home/howto/PERSISTENT_STORAGE.md
> +[NFS](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) storage documentation. There is another way exists
```suggestion
[NFS](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) storage documentation. There is another way
```

2021-10-04 07:17 UTC, plirglo approved these changes

2021-10-04 07:28 UTC, seriva approved these changes

2021-10-04 07:30 UTC, merged