Restructure of data directory
epiphany-platform/epiphany pull request #2671
Opened 2021-10-06 11:57 UTC by seriva

- Moved unit tests.
- Moved spec tests.
- Moved ansible sources.
- Move terraform templates.
- Rename data to schema.
- Restructure container builds.
- Fix paths to project wide.
- Fixed Prometheus validation, needed one more tab for a section.
- Added missing tests from @erzetpe from this pull #2576 as her forgot to merge that branch into develop

2021-10-06 14:25 UTC, to-bar requested changes

2021-10-06 14:25 UTC, to-bar commented on Dockerfile
> +    && : INSTALL ISTIOCTl BINARY \
```suggestion
    && : INSTALL ISTIOCTL BINARY \
```

2021-10-06 14:28 UTC, to-bar submitted a review, later dismissed

2021-10-06 14:57 UTC, przemyslavic commented
/azp run

2021-10-06 16:10 UTC, przemyslavic commented
/azp run

2021-10-06 16:51 UTC, to-bar submitted a review, later dismissed

2021-10-06 18:13 UTC, przemyslavic commented
/azp run

2021-10-06 19:31 UTC, przemyslavic commented
/azp run

2021-10-06 21:22 UTC, przemyslavic commented
This time there is a permission issue:
```
2021-10-06T21:19:57.5553638Z [command]/usr/local/bin/docker run --rm -v /tmp/build/epi-cli:/shared epiphanyregistry.azurecr.io/epicli:merge.5729 -c epicli -h
2021-10-06T21:19:58.1336689Z /bin/bash: line 1: /bin/epicli: Permission denied
2021-10-06T21:19:58.5187486Z ##[error]/bin/bash: line 1: /bin/epicli: Permission denied
2021-10-06T21:19:58.5227687Z ##[error]The process '/usr/local/bin/docker' failed with exit code 126
```

Even if executed from inside the container:
```
epiuser@71f02b052e28:/shared$ epicli -h
bash: /bin/epicli: Permission denied
```

2021-10-07 06:05 UTC, seriva commented
> This time there is a permission issue:
> 
> ```
> 2021-10-06T21:19:57.5553638Z [command]/usr/local/bin/docker run --rm -v /tmp/build/epi-cli:/shared epiphanyregistry.azurecr.io/epicli:merge.5729 -c epicli -h
> 2021-10-06T21:19:58.1336689Z /bin/bash: line 1: /bin/epicli: Permission denied
> 2021-10-06T21:19:58.5187486Z ##[error]/bin/bash: line 1: /bin/epicli: Permission denied
> 2021-10-06T21:19:58.5227687Z ##[error]The process '/usr/local/bin/docker' failed with exit code 126
> ```
> 
> Even if executed from inside the container:
> 
> ```
> epiuser@71f02b052e28:/shared$ epicli -h
> bash: /bin/epicli: Permission denied
> ```

mmm not seeing it here under Windows. Will check WSL2.

2021-10-07 06:38 UTC, seriva commented
> > This time there is a permission issue:
> > ```
> > 2021-10-06T21:19:57.5553638Z [command]/usr/local/bin/docker run --rm -v /tmp/build/epi-cli:/shared epiphanyregistry.azurecr.io/epicli:merge.5729 -c epicli -h
> > 2021-10-06T21:19:58.1336689Z /bin/bash: line 1: /bin/epicli: Permission denied
> > 2021-10-06T21:19:58.5187486Z ##[error]/bin/bash: line 1: /bin/epicli: Permission denied
> > 2021-10-06T21:19:58.5227687Z ##[error]The process '/usr/local/bin/docker' failed with exit code 126
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even if executed from inside the container:
> > ```
> > epiuser@71f02b052e28:/shared$ epicli -h
> > bash: /bin/epicli: Permission denied
> > ```
> 
> mmm not seeing it here under Windows. Will check WSL2.

![image](https://user-images.githubusercontent.com/11056665/136332094-25ad695a-4464-4b73-8534-3a7bacb0dcca.png)

![image](https://user-images.githubusercontent.com/11056665/136332148-3cac1d45-cb72-4398-bfe9-eddacf934ea0.png)

So yeah, on WSL2 I get the same. Interesting how there still these differences between docker desktop on Windows and WSL2 as they share the same context....

2021-10-07 06:53 UTC, seriva commented
> bash: /bin/epicli: Permission denied

![image](https://user-images.githubusercontent.com/11056665/136334173-abfe2d9f-646b-4ede-bac2-ea0d70453e48.png)
 Should be fixed.

2021-10-07 06:56 UTC, przemyslavic commented
/azp run

2021-10-07 07:10 UTC, przemyslavic commented
way better 👍

2021-10-07 07:43 UTC, to-bar requested changes

2021-10-07 07:43 UTC, to-bar commented on epicli
> +python3 -m cli.epicli $@
```suggestion
python3 -m cli.epicli "$@"
```
https://github.com/koalaman/shellcheck/wiki/SC2068

2021-10-07 07:54 UTC, seriva commented on epicli
> +python3 -m cli.epicli $@
Fixed.

2021-10-07 08:13 UTC, to-bar approved these changes

2021-10-07 08:17 UTC, przemyslavic commented
/azp run

2021-10-07 10:00 UTC, przemyslavic approved these changes

2021-10-07 10:08 UTC, merged