Updated backup-restore doc
epiphany-platform/epiphany pull request #2676
Opened 2021-10-07 11:45 UTC by atsikham

Additional change requested in the scope of #1974

2021-10-07 15:32 UTC, to-bar requested changes

2021-10-07 15:32 UTC, to-bar commented on docs/home/howto/BACKUP.md
> +If backup config is attached to cluster-config.yml, use this file instead ``backup.yml``
```suggestion
If backup config is attached to cluster-config.yml, use this file instead of ``backup.yml``.
```

2021-10-07 15:32 UTC, to-bar commented on docs/home/howto/BACKUP.md
> +If recovery config is attached to cluster-config.yml, use this file instead ``recovery.yml``
```suggestion
If recovery config is attached to cluster-config.yml, use this file instead of ``recovery.yml``.
```

2021-10-08 07:20 UTC, atsikham commented on docs/home/howto/BACKUP.md
> +If recovery config is attached to cluster-config.yml, use this file instead ``recovery.yml``
Not my cow  😄

2021-10-08 07:54 UTC, to-bar approved these changes

2021-10-08 08:00 UTC, seriva approved these changes

2021-10-08 08:01 UTC, merged