Refactor PostgreSQL upgrade
epiphany-platform/epiphany pull request #2708
Opened 2021-10-14 16:00 UTC by to-bar

2021-10-14 20:19 UTC, to-bar commented
/azp run

2021-10-15 11:02 UTC, atsikham requested changes
Does documentation about rollback need to be updated?

2021-10-15 11:02 UTC, atsikham commented on ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/start-and-enable-service.yml
> ----
?

2021-10-15 11:02 UTC, atsikham commented on ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> -- name: PostgreSQL | Include manifest from 'postgresql' role
Previously for upgrade we marked which component tasks belong to as there is an ability to execute upgrade for all/few components. Do we plan change that?

2021-10-15 12:32 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/upgrade/extensions/replication/pg-new/start-and-enable-service.yml
> ----
It wasn't intentional change 😉 just branch integration issue.

2021-10-15 12:40 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/upgrade/main.yml
> -- name: PostgreSQL | Include manifest from 'postgresql' role
Yes we marked because for other roles we have upgrade tasks inside the `upgrade` role. For PostgreSQL we have upgrade tasks inside the `postgresql` role so we have information in Ansible's output that upgrade is running for `postgresql` component. For this reason I see printing `PostgreSQL |` prefix as redundant information.

2021-10-15 12:42 UTC, atsikham submitted a review, later dismissed
🥇

2021-10-15 12:46 UTC, to-bar commented
> 
> 
> Does documentation about rollback need to be updated?

We do not have rollback documented yet.

2021-10-15 13:27 UTC, przemyslavic commented
I'm facing issues upgrading PostgreSQL (epicli v1.1 to develop) on Ubuntu.
```
12:47:06 INFO cli.engine.ansible.AnsibleCommand - TASK [postgresql : PostgreSQL | Extensions | repmgr | Install package(s) for PostgreSQL 13] ***
12:47:07 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-x-x-x-x.eu-west-1.compute.amazonaws.com]: FAILED! => {"cache_update_time": 1634300598, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'postgresql-13-repmgr=5.2.1-*' 'repmgr-common=5.2.1-*'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.\n", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  postgresql-13-repmgr\nThe following packages will be DOWNGRADED:\n  repmgr-common\n0 upgraded, 1 newly installed, 1 downgraded, 0 to remove and 25 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  postgresql-13-repmgr", "The following packages will be DOWNGRADED:", "  repmgr-common", "0 upgraded, 1 newly installed, 1 downgraded, 0 to remove and 25 not upgraded."]}
```
 I see this PR should solve it, right? :)

2021-10-15 13:45 UTC, to-bar commented
> I see this PR should solve it, right? :)

Yes, I found the same issue yesterday and included [fix](https://github.com/epiphany-platform/epiphany/pull/2708/commits/002f1f60c2af0051dab57a4d91600fbb9573780a) in this PR.

2021-10-20 08:59 UTC, seriva submitted a review, later dismissed

2021-10-20 11:54 UTC, seriva approved these changes

2021-10-20 11:55 UTC, atsikham approved these changes

2021-10-20 12:33 UTC, merged