Add tests for docker and kubelet cgroup driver
epiphany-platform/epiphany pull request #2711
Opened 2021-10-15 14:37 UTC by przemyslavic

Task #2703.
Useful for testing Kubernetes upgrade #2696.

2021-10-15 15:46 UTC, to-bar submitted a review, later dismissed

2021-10-15 15:52 UTC, to-bar commented
@przemyslavic You can consider adding this task to changelog :slightly_smiling_face:

2021-10-15 18:20 UTC, przemyslavic commented
Done ☺️

2021-10-15 18:46 UTC, atsikham requested changes

2021-10-15 18:46 UTC, atsikham commented on tests/spec/spec/kubernetes_master/kubernetes_master_spec.rb
> +describe 'Check the container runtime cgroup driver' do
In our case container runtime is Docker, and here different thing is checked, so I would change description.

2021-10-15 18:46 UTC, atsikham commented on tests/spec/spec/kubernetes_node/kubernetes_node_spec.rb
> +describe 'Check the container runtime cgroup driver' do
Same here.

2021-10-15 22:02 UTC, atsikham commented
In our [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/CERTIFICATES.md) we have such statement:

```
kubelet.conf is not renewed because kubelet is configured for automatic certificate renewal. To verify that, navigate to /var/lib/kubelet/ and check config.yaml file, where rotateCertificates setting is true by default.
```

We could check `rotateCertificates` here the same way as `cgroupDriver` (in ConfigMap and `/var/lib/kubelet/config.yaml`).

WDYT about adding it here without an additional task?

2021-10-18 08:28 UTC, atsikham approved these changes
Great to see this done so quick!

2021-10-18 08:40 UTC, erzetpe approved these changes

2021-10-18 08:41 UTC, merged