Automatic postgres clustering
epiphany-platform/epiphany pull request #2721
Opened 2021-10-25 11:36 UTC by erzetpe

2021-10-25 11:54 UTC, plirglo submitted a review, later dismissed

2021-10-25 12:04 UTC, przemyslavic commented
/azp run

2021-10-25 13:02 UTC, przemyslavic commented
It would be nice to have this updated in postgresql tests as well:
https://github.com/epiphany-platform/epiphany/blob/develop/tests/spec/spec/postgresql/postgresql_spec.rb#L38
`replicated =           config_docs[:postgresql]["specification"]["extensions"]["replication"]["enabled"]`

`replicated =           countInventoryHosts("postgresql") > 1` or something similar

2021-10-25 13:39 UTC, przemyslavic commented
/azp run

2021-10-25 17:00 UTC, przemyslavic commented
Please do not merge yet, even if it is approved.

2021-10-26 07:12 UTC, przemyslavic commented
1. Backup and recovery doesn't work properly. There are many tasks depending on the condition
`when: component_vars.specification.extensions.replication.enabled | default(false)`, which are skipped as the default value is `False` (as we do not have this parameter in the specification).
2. Upgrade from 1.3.0dev to 1.3.0dev fails on preflight check :
```
The conditional check 'pg_manifest.specification.extensions.replication.enabled' failed. The error was: error while evaluating conditional (pg_manifest.specification.extensions.replication.enabled): 'dict object' has no attribute 'enabled'.
```
```
15:56:35 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Check if PostgreSQL 10 cluster is healthy] *******************
15:56:35 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-1-1-1-1.eu-west-3.compute.amazonaws.com]: FAILED! => {"msg": "The conditional check 'pg_manifest.specification.extensions.replication.enabled' failed. The error was: error while evaluating conditional (pg_manifest.specification.extensions.replication.enabled): 'dict object' has no attribute 'enabled'\n\nThe error appears to be in '/shared/build/devawsrhelflannel/ansible/roles/postgresql/tasks/preflight/upgrade.yml': line 160, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Check if PostgreSQL {{ pg_old.pg.version }} cluster is healthy\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
15:56:35 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-2-2-2-2.eu-west-3.compute.amazonaws.com]: FAILED! => {"msg": "The conditional check 'pg_manifest.specification.extensions.replication.enabled' failed. The error was: error while evaluating conditional (pg_manifest.specification.extensions.replication.enabled): 'dict object' has no attribute 'enabled'\n\nThe error appears to be in '/shared/build/devawsrhelflannel/ansible/roles/postgresql/tasks/preflight/upgrade.yml': line 160, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Check if PostgreSQL {{ pg_old.pg.version }} cluster is healthy\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```
While it might not make much sense to do such an upgrade, in my opinion it should work anyway. Additionally, it means that if we release 1.3.0, this problem will definitely occur when trying to upgrade to 2.0.0dev, so in my opinion this should be fixed now, not that you have to remember about it in the future..
I think all playbooks that use the `specification.extensions.replication.enabled` parameter has to be reviewed and refactored (e.g. change `specification.extensions.replication.enabled` to `groups.postgresql | length > 1`). Another option is to keep the parameter in the manifest file, then you do not have to change other playbooks, but set the value automatically, if it's possible.
3. Please also update the schema validation.
4. We do not support replication for aarch64 and now it looks like it will be enabled automatically for 2 nodes.

2021-10-26 18:51 UTC, atsikham requested changes
Please update Molecule tests/configuration - `replication.enabled` should be also removed there.

2021-10-29 07:11 UTC, przemyslavic commented
/azp run

2021-10-29 07:59 UTC, przemyslavic commented on ansible/playbooks/roles/postgresql/tasks/preflight/apply.yml
> +        - ansible_architecture == 'arm64'
Does not work properly for aarch64.
Ansible is skipping this task:
```
2021-10-29T07:57:01.5564718Z [38;21m07:57:01 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Assert no multiple nodes for ARM] ****************************[0m
2021-10-29T07:57:01.6216419Z [38;21m07:57:01 INFO cli.engine.ansible.AnsibleCommand - skipping: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com][0m
```

2021-10-29 08:47 UTC, przemyslavic commented
/azp run

2021-10-29 09:34 UTC, przemyslavic commented on ansible/playbooks/roles/postgresql/tasks/main.yml
> +              "{{ ansible_architecture == 'x86_64' and groups['postgresql'] | length > 1 }}"
There is something wrong with it as it enables replication for aarch64:
```
2021-10-29T09:08:15.5432333Z [38;21m09:08:15 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Check if PostgreSQL extensions are supported for the architecture] ***
2021-10-29T09:08:15.6571478Z [31;21m09:08:15 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com -> localhost]: FAILED! => {
2021-10-29T09:08:15.6572673Z [38;21m09:08:15 INFO cli.engine.ansible.AnsibleCommand -     "assertion": "_unsupported_enabled_extensions | length == 0",
2021-10-29T09:08:15.6573852Z [38;21m09:08:15 INFO cli.engine.ansible.AnsibleCommand -     "changed": false,
2021-10-29T09:08:15.6575065Z [38;21m09:08:15 INFO cli.engine.ansible.AnsibleCommand -     "evaluated_to": false,
2021-10-29T09:08:15.6582830Z [38;21m09:08:15 INFO cli.engine.ansible.AnsibleCommand -     "msg": "replication extensions are not supported\n  for aarch64 and cannot be installed"

2021-11-02 10:16 UTC, przemyslavic commented
/azp run

2021-11-02 12:45 UTC, przemyslavic commented
/azp run

2021-11-03 09:25 UTC, atsikham requested changes, later dismissed

2021-11-03 09:25 UTC, atsikham commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +  - name: Debag
Needed? If yes, there is a typo.

2021-11-03 09:34 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +  - name: Debag
Not needed. Removed.

2021-11-03 14:29 UTC, przemyslavic commented
/azp run

2021-11-03 14:33 UTC, przemyslavic commented
/azp run

2021-11-03 15:09 UTC, przemyslavic commented
/azp run

2021-11-03 16:40 UTC, przemyslavic approved these changes, later dismissed

2021-11-05 16:07 UTC, to-bar requested changes

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/main.yml
> +
```suggestion
- name: Set replication as enabled
  when:
    - groups.postgresql | count > 1
    - ansible_architecture == 'x86_64'
  set_fact:
    specification: "{{ specification | combine(_spec, list_merge='append', recursive=True) }}"
  vars:
    _spec: { extensions: { replication: { enabled: true } } }
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/preflight/apply.yml
> +        postgresql: "{{ postgresql | combine(_spec, list_merge='append', recursive=True) }}"
```suggestion
    - name: Set replication as enabled
      when:
        - groups.postgresql | count > 1
        - ansible_architecture == 'x86_64'
      set_fact:
        postgresql: "{{ postgresql | combine(_spec, list_merge='append', recursive=True) }}"
      vars:
        _spec: { specification: { extensions: { replication: { enabled: true } } } }
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +      _pg_old_replication_enabled: "{{ stat_repmgr_config_file.stat.exists and not (config_file_header.stdout_lines[1] is defined and config_file_header.stdout_lines[1] is match('# repmgr sample conf
```suggestion
      pg_old_replication_enabled: "{{ stat_repmgr_config_file.stat.exists and not (config_file_header.stdout_lines[1] is defined and config_file_header.stdout_lines[1] is match('# repmgr sample configuration file')) }}"
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +    - _pg_old_replication_enabled
```suggestion
    - pg_old_replication_enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +    that: groups.postgresql | count < 2 or _pg_old_replication_enabled
```suggestion
    that: groups.postgresql | count < 2 or pg_old_replication_enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +    fail_msg: Upgrade is not supported for configurations with more than one PostgreSQL primary node
```suggestion
    fail_msg: Upgrade is not supported for configuration with more than one PostgreSQL primary node
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +- name: Check if replication previously enabled
```suggestion
- name: Check if replication was enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +  - name: Check if replication previously enabled | Check if config file exists
```suggestion
  - name: Check if replication was enabled | Check if config file exists
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +  - name: Check if replication previously enabled | RedHat | Check if config file is from package
```suggestion
  - name: Check if replication was enabled | RedHat | Check if config file is from package
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +  - name: Check if replication previously enabled | Set previous version clustered status
```suggestion
  - name: Check if replication was enabled | Set fact
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +  when: _replication_previously_enabled
```suggestion
  when: replication_enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +      when: _replication_previously_enabled
```suggestion
      when: replication_enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +    - _replication_previously_enabled
```suggestion
    - replication_enabled
```

2021-11-05 16:07 UTC, to-bar commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +
```suggestion
      replication_enabled: "{{ stat_repmgr_config_file.stat.exists and not (config_file_header.stdout_lines[1] is defined and config_file_header.stdout_lines[1] is match('# repmgr sample configuration file')) }}"
```

2021-11-05 16:07 UTC, to-bar commented on docs/home/howto/DATABASES.md
> +secondary server with replication user with name and password specified in configuration file.
```suggestion
If the number of PostgreSQL nodes is higher than one, Epiphany will automatically create a cluster of primary and
standby server(s) with replication users with name and password specified in configuration file.
```

2021-11-09 09:34 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/apply.yml
> +        postgresql: "{{ postgresql | combine(_spec, list_merge='append', recursive=True) }}"
This code will broke because of the undefined treated as enabled.

2021-11-09 09:35 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/apply.yml
> +        postgresql: "{{ postgresql | combine(_spec, list_merge='append', recursive=True) }}"
This code will break because of the undefined treated as enabled.

2021-11-09 09:35 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/main.yml
> +
This code will break because of the undefined treated as enabled.

2021-11-09 13:26 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +      _pg_old_replication_enabled: "{{ stat_repmgr_config_file.stat.exists and not (config_file_header.stdout_lines[1] is defined and config_file_header.stdout_lines[1] is match('# repmgr sample conf
Done.

2021-11-09 13:27 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +    - _pg_old_replication_enabled
Done.

2021-11-09 13:30 UTC, erzetpe commented on ansible/playbooks/roles/postgresql/tasks/preflight/upgrade.yml
> +    that: groups.postgresql | count < 2 or _pg_old_replication_enabled
Done.

2021-11-09 13:48 UTC, erzetpe commented on docs/home/howto/DATABASES.md
> +secondary server with replication user with name and password specified in configuration file.
Done.

2021-11-09 14:23 UTC, erzetpe commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +  when: _replication_previously_enabled
Done.

2021-11-09 14:23 UTC, erzetpe commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +      when: _replication_previously_enabled
Done.

2021-11-09 14:23 UTC, erzetpe commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +    - _replication_previously_enabled
Done.

2021-11-09 14:27 UTC, erzetpe commented on ansible/playbooks/roles/recovery/tasks/postgresql.yml
> +
Done.

2021-11-09 15:52 UTC, to-bar approved these changes

2021-11-10 07:32 UTC, atsikham approved these changes

2021-11-10 12:32 UTC, przemyslavic commented
/azp run

2021-11-15 09:04 UTC, przemyslavic commented
/azp run

2021-11-15 11:47 UTC, przemyslavic approved these changes

2021-11-15 12:04 UTC, merged