RabbitMQ monitoring automation (#1487)
epiphany-platform/epiphany pull request #2729
Opened 2021-10-26 21:01 UTC by sbbroot

* Enable RabbitMQ's plugin for Prometheus metrics exposure

* Add target for Prometheus to be able to scrape metrics from rabbitmq nodes

* Download Grafana dashboard for displaying scraped metrics from RabbitMQ

2021-10-29 11:11 UTC, plirglo submitted a review, later dismissed

2021-10-29 11:17 UTC, seriva commented on schema/common/defaults/configuration/shared-config.yml
> +  rabbitmq_monitoring_enabled: False
For me this is not something that should live in shared config.

2021-10-29 11:18 UTC, seriva commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +          - dashboard_id: '10991'
Should dashboard_id and datasource be configurable? What do we have with other data collecting plugins?

2021-10-29 12:45 UTC, sbbroot commented on schema/common/defaults/configuration/shared-config.yml
> +  rabbitmq_monitoring_enabled: False
I'm open for suggestions, I put it here because it is needed across multiple roles.

2021-10-29 12:46 UTC, sbbroot commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +          - dashboard_id: '10991'
This is the single official RabbitMQ dashboard for Grafana. I don't think it needs to be configurable.

2021-10-29 13:52 UTC, przemyslavic commented
Traffic on port 15692 should be allowed to be able to scrape metrics.

2021-11-02 08:22 UTC, przemyslavic commented
@sbbroot network security groups have yet to be updated:
https://github.com/epiphany-platform/epiphany/blob/develop/schema/aws/defaults/infrastructure/virtual-machine.yml
https://github.com/epiphany-platform/epiphany/blob/develop/schema/azure/defaults/infrastructure/virtual-machine.yml

2021-11-10 10:23 UTC, to-bar requested changes

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +    - name: Set facts for RabbitMQ dashboard
```suggestion
    - name: Set fact for RabbitMQ dashboard
```

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +        grafana_external_dashboards: "{{ grafana_external_dashboards + rabbitmq_dashboard }}"
```suggestion
        grafana_external_dashboards: "{{ grafana_external_dashboards | union(rabbitmq_dashboard) }}"
```
`union` is for adding when not exists (uniqueness)

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +            datasource: 'Prometheus'
```suggestion
            datasource: Prometheus
```

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/dashboards.yml
> +      when:
The same conditions in `when` is used for adjacent tasks, please consider using block to have just one common `when`.

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/main.yml
> +    name: specification.rabbitmq_monitoring_enabled
`name` parameter means that ALL content is loaded under the name, not that variable with this name is loaded.

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/prometheus/tasks/configure.yml
> +    name: specification.rabbitmq_monitoring_enabled
`name` parameter means that ALL content is loaded under the name, not that variable with this name is loaded.

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/main.yml
> +  when: groups.rabbitmq is defined | count > 0
Does it work?
It looks like calling `count` on boolean.

Standard syntax is:
```
when:
  - groups.rabbitmq is defined
  - groups.rabbitmq | count
 ```

2021-11-10 10:23 UTC, to-bar commented on ansible/playbooks/roles/prometheus/templates/prometheus.yml.j2
> +          - "{{ rabbitmq_instance }}:15692"
```suggestion
      {% for rabbitmq_node in groups['rabbitmq'] %}
          - "{{ rabbitmq_node }}:15692"
```

2021-11-10 10:23 UTC, to-bar commented on schema/common/defaults/configuration/rabbitmq.yml
> +  rabbitmq_monitoring_enabled: false
Please update schema/common/validation/configuration/rabbitmq.yml

2021-11-10 10:23 UTC, to-bar commented on schema/common/defaults/configuration/rabbitmq.yml
> +
```suggestion
```

2021-11-10 10:23 UTC, to-bar commented on schema/common/defaults/configuration/firewall.yml
> +        - 15692/tcp   # rabbitmq-exporter for Prometheus
Please add this port to docs/home/SECURITY.md

2021-11-10 13:34 UTC, to-bar commented on ansible/playbooks/roles/prometheus/tasks/configure.yml
> +- name: Set fact for RabbitMQ monitoring var
```suggestion
- name: Set fact about RabbitMQ monitoring
```

2021-11-10 13:34 UTC, to-bar commented on ansible/playbooks/roles/grafana/tasks/main.yml
> +- name: Set fact for RabbitMQ monitoring var
```suggestion
- name: Set fact about RabbitMQ monitoring
```

2021-11-10 13:49 UTC, to-bar approved these changes, later dismissed

2021-11-10 13:56 UTC, erzetpe submitted a review, later dismissed

2021-11-10 13:58 UTC, to-bar submitted a review, later dismissed

2021-11-10 14:06 UTC, erzetpe submitted a review, later dismissed

2021-11-15 12:25 UTC, przemyslavic commented
/azp run

2021-11-15 12:51 UTC, przemyslavic commented
/azp run

2021-11-15 13:16 UTC, przemyslavic commented on schema/aws/defaults/infrastructure/virtual-machine.yml
> +       description: Allow Prometheus for RabbitMQ's data scrap
Description causes issues on AWS:
`Error: "ingress.3.description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\;\\{\\}\\!\\$\\*]*$"): "7 - Allow Prometheus for RabbitMQ's data scrap"`

2021-11-15 14:00 UTC, przemyslavic commented
/azp run

2021-11-16 11:42 UTC, przemyslavic submitted a review, later dismissed

2021-11-16 11:45 UTC, erzetpe submitted a review, later dismissed

2021-11-16 11:47 UTC, erzetpe approved these changes

2021-11-16 11:49 UTC, przemyslavic approved these changes

2021-11-16 11:50 UTC, merged