Add sorting entries in the inventory file (#1076)
epiphany-platform/epiphany pull request #2733
Opened 2021-10-29 07:28 UTC by sbbroot

* Add sorting hostnames for `Azure` and `Any` provider in the inventory
  file

2021-11-05 09:41 UTC, seriva approved these changes
Looks good. Don't care for the TestCase wrapping but that's partially preferences ;)

2021-11-05 09:41 UTC, seriva commented on tests/unit/engine/providers/data/APIProxy_data.py
> +RUNNING_INSTANCES: List[List[Dict]] = [
This would be specific to Azure, maybe name it something like RUNNING_INSTANCES_AZURE?

2021-11-05 17:10 UTC, seriva requested changes
Missed the use of unittest in your imports as PawoG noted. We chose pytest over unittest. so pls rewrite these tests in pytests.

2021-11-08 14:43 UTC, erzetpe submitted a review, later dismissed

2021-11-08 14:48 UTC, erzetpe submitted a review, later dismissed

2021-11-08 14:58 UTC, seriva approved these changes, later dismissed

2021-11-17 08:53 UTC, przemyslavic commented
/azp run

2021-11-17 09:03 UTC, przemyslavic commented
/azp run

2021-11-17 16:13 UTC, przemyslavic submitted a review, later dismissed

2021-11-17 21:14 UTC, przemyslavic approved these changes

2021-11-18 07:32 UTC, erzetpe approved these changes

2021-11-18 07:33 UTC, merged