Fix postgres nodes assertion.
epiphany-platform/epiphany pull request #2811
Opened 2021-12-22 12:09 UTC by seriva

2021-12-22 12:52 UTC, atsikham requested changes

2021-12-22 12:52 UTC, atsikham commented on cli/engine/ApplyEngine.py
> +                        if key in components:
May be combine them?

2021-12-22 12:56 UTC, plirglo approved these changes, later dismissed

2021-12-22 13:32 UTC, seriva commented on cli/engine/ApplyEngine.py
> +                        if key in components:
Good point.

2021-12-22 13:34 UTC, plirglo approved these changes

2021-12-22 13:36 UTC, atsikham approved these changes

2021-12-23 11:21 UTC, atsikham commented
Checked different combinations of scaling up/down and feature mapping for apply. Everything works as expected - there is an error message in case of PostgreSQL nodes number change.

2021-12-28 09:24 UTC, przemyslavic commented
@seriva I think it can be merged as it has already been tested by @atsikham.

2021-12-28 09:43 UTC, merged