Kafka upgrade (#2871)
epiphany-platform/epiphany pull request #2990
Opened 2022-02-22 14:15 UTC by cicharka

* Kafka: Upgrade to 2.8.1 version

* Kafka: Refactor installation and upgrade tasks

* Kafka: move upgrade tasks to Kafka role

* Zookeeper: refactor installation and upgrade

* Zookeeper: move upgrade tasks to Zookeeper role

2022-02-28 12:31 UTC, przemyslavic commented
Don't we want to update ZooKeeper to v3.5.9? https://issues.apache.org/jira/browse/KAFKA-12310

2022-02-28 13:30 UTC, cicharka commented
> Don't we want to update ZooKeeper to v3.5.9? https://zookeeper.apache.org/doc/r3.5.9/releasenotes.html It comes with Kafka 2.8.0.

I think that I didn't take it into account because:
* documentation of Ecosystem for Kafka 2.8.1 says nothing about Zookeeper upgrade -> it only mention that in Kafka 2.5.0 ZooKeeper has been upgraded to 3.5.7. Additionally I have not checked Kafka archive in order to investigate Zookeeper version which comes with it (didn't know about it to be honest)
* I checked that Kafka doesn't specify Zookeeper version required, and as we are installing it as standalone component and I have not found any issues that states to upgrade it, I just skipped it

However, since you asked about it, and even found that it comes with Kafka, we can think about 2 options:
1. We are going to remove ZooKeeper role since it is only used as prerequisite for Kafka (for my understanding, if it's not true please correct me) and we are going to use Zookeeper that comes with Kafka (additionally Kafka states that they already removed ZooKeeper from Kafka, but still in development stage)
2. We are going only to upgrade ZooKeeper version -> ZooKeeper role will stay, only defaults and binary changed needed.

I don't know about any other ZooKeeper usecases but if its only Kafka's prerequisite I would vote for role removal and move to use ZooKeeper that comes with Kafka. (I would also do it in another PR to do not overwhelm reviewers :) )
Sorry for long post!

2022-03-01 13:01 UTC, rafzei requested changes

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/common/download_and_unpack_binary.yml
> +
```suggestion

```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/common/stop.yml
> +
```suggestion

```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
>      mode: "0755"
Some time ago we agreed to use symbolic modes
```suggestion
    mode: u=rwx,go=rx
```
BTW do we need that wide permissions? (please check also in other places)

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: keytool -keystore {{ specification.security.ssl.server.keystore_location }} \
I would use `command` here and in other places w/o chars like <,>, |  and &

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/metrics.yml
>      mode: 0644
```suggestion
    mode: u=rx,go=r
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/setup-kafka.yml
>      mode: 0755
```suggestion
    mode: u=rwx,go=rx
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/setup-kafka.yml
>      mode: 0755
```suggestion
    mode: u=rwx,go=rx
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/setup-kafka.yml
>      mode: 0755
```suggestion
    mode: u=rwx,go=rx
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/setup-kafka.yml
>      mode: 0644
```suggestion
    mode: u=rw,go=r
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/setup-kafka.yml
>      mode: 0644
```suggestion
    mode: u=rw,go=r
```

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: keytool -list -v -keystore {{ specification.security.ssl.server.keystore_location }} \
I would add `set -o pipefail` here

2022-03-01 13:01 UTC, rafzei commented on ansible/playbooks/roles/zookeeper/tasks/main.yml
> +  # force: ?
:smiley_cat:

2022-03-01 14:57 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: keytool -keystore {{ specification.security.ssl.server.keystore_location }} \
That was the only place where we are not using any shell operators, so I only changed it in this line.

2022-03-01 14:58 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: keytool -list -v -keystore {{ specification.security.ssl.server.keystore_location }} \
done.

2022-03-01 14:59 UTC, cicharka commented on ansible/playbooks/roles/zookeeper/tasks/main.yml
> +  # force: ?
yeah :( fixed now!

2022-03-02 11:03 UTC, erzetpe requested changes

2022-03-02 11:03 UTC, erzetpe commented on ansible/playbooks/roles/kafka/tasks/common/download_and_unpack_binary.yml
> +    group: kafka
This probably should be taken from vars?

2022-03-02 11:03 UTC, erzetpe commented on ansible/playbooks/roles/kafka/tasks/upgrade/install-upgrade.yml
> +    state: absent
We should confirm that we have something about backup or put some flag to left the people decision if they want to remove old binaries.

2022-03-04 07:47 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/common/download_and_unpack_binary.yml
> +    group: kafka
Taken from specification as we let user configure that.

2022-03-04 07:47 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/upgrade/install-upgrade.yml
> +    state: absent
Added note in Upgrade docs

2022-03-04 09:15 UTC, rafzei submitted a review, later dismissed
LGTM

2022-03-04 11:44 UTC, atsikham requested changes
This PR also can be the place for this task - https://github.com/epiphany-platform/epiphany/issues/2235. As I see, openjdk 8 is used only for Kafka and Zookeeper.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/common/download_and_unpack_binary.yml
> +    remote_src: yes
We agreed some time before to use `true/false` values, please change in each affected place.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/common/stop.yml
> +---
Is it needed to be stored in a separate file? Same for start.yml.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +    path: "{{ specification.security.ssl.server.keystore_location | dirname }}/ca-cert"
Add `get_*` parameters with `false` value where it's possible.
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: openssl req -new -x509 -keyout {{ specification.security.ssl.server.keystore_location | dirname }}/ca-key \
Change `shell` module to `command` where it's possible, like it's done above.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
>    fetch:
May be changed to `slurp` not to store local files.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/metrics.yml
>    with_inventory_hostnames:
I suggest to use `loop` to follow the same standard as we have in other places.

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/upgrade/main.yml
> +  include_tasks: upgrade/preflight-check.yml
In `postgresql` role we have the `preflight` directory, what do you think about doing the same here?

2022-03-04 11:44 UTC, atsikham commented on ansible/playbooks/roles/kafka/tasks/upgrade/main.yml
> +- name: Set old Kafka version fact
How about usage of the fact's name here? `old_kafka_version `

2022-03-04 12:34 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/common/stop.yml
> +---
start.yml was already in separate file so I only [moved it to common](https://github.com/epiphany-platform/epiphany/pull/2990/files/13f1487d2d1082019b1e57cc51725dd70d3176f9#diff-42a0c302e962e0a498efae3dd5167585a4703e00bc935533284ff0f58408feff), and I did the same for stop.yml just to be consistent with let's call it, 'common tools'.
I know that it is not the biggest improvement...

2022-03-04 12:35 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/common/download_and_unpack_binary.yml
> +    remote_src: yes
Ok, I will review other places as well

2022-03-04 12:36 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/generate-certificates.yml
> +  shell: openssl req -new -x509 -keyout {{ specification.security.ssl.server.keystore_location | dirname }}/ca-key \
Not possible in other places, due to the fact that they are using shell options like pipes etc.
Already corrected all of them based on @rafzei comments.

2022-03-04 13:08 UTC, cicharka commented on ansible/playbooks/roles/kafka/tasks/upgrade/main.yml
> +  include_tasks: upgrade/preflight-check.yml
I checked it now, cool idea -> but Kafka doesn't have any preflight checks file for apply.

But it doesn't mean we cannot adapt that idea in Kafka:
Task `- name: Check if jmx exporter is available`
from `tasks/main.yml` can be extracted into newly created `tasks/prefilight/apply.yml`, and `upgrade/preflight-check.yml` can be moved into `tasks/preflight/upgrade.yml`.

As additional note, I would encourage ourselves to note that approach and let other developers know about that structure.

2022-03-07 15:53 UTC, atsikham approved these changes, later dismissed

2022-03-08 11:10 UTC, rafzei commented
@cicharka One more thing, could you please run ansible-lint task in devcontainer on Kafka playbook and fix the issues?

2022-03-08 13:17 UTC, cicharka commented
/azp run

2022-03-09 08:52 UTC, seriva submitted a review, later dismissed

2022-03-09 13:23 UTC, erzetpe submitted a review, later dismissed

2022-03-09 13:35 UTC, cicharka commented
/azp run

2022-03-11 08:34 UTC, atsikham approved these changes, later dismissed

2022-03-23 10:43 UTC, atsikham submitted a review, later dismissed

2022-03-23 11:00 UTC, przemyslavic commented
/azp run

2022-03-23 12:18 UTC, przemyslavic commented
:x: It fails when there is no monitoring component enabled:
```
2022-03-23T11:45:38.0521213Z [38;21m11:45:38 INFO cli.src.ansible.AnsibleCommand - TASK [kafka : delegated | create prometheus system group] **********************[0m
2022-03-23T11:45:38.0781789Z [31;21m11:45:38 ERROR cli.src.ansible.AnsibleCommand - fatal: [ci-kfkawsrhelflannel-kafka-vm-0 -> {{ node }}]: FAILED! => {"msg": "'dict object' has no attribute 'prometheus'"}[0m
2022-03-23T11:45:38.1062569Z [31;21m11:45:38 ERROR cli.src.ansible.AnsibleCommand - fatal: [ci-kfkawsrhelflannel-kafka-vm-1 -> {{ node }}]: FAILED! => {"msg": "'dict object' has no attribute 'prometheus'"}[0m
2022-03-23T11:45:38.1160160Z [31;21m11:45:38 ERROR cli.src.ansible.AnsibleCommand - fatal: [ci-kfkawsrhelflannel-kafka-vm-2 -> {{ node }}]: FAILED! => {"msg": "'dict object' has no attribute 'prometheus'"}[0m
2022-03-23T11:45:38.1162720Z [38;21m11:45:38 INFO cli.src.ansible.AnsibleCommand - [0m
```

2022-03-23 12:43 UTC, przemyslavic commented
/azp run

2022-03-23 12:59 UTC, seriva approved these changes, later dismissed

2022-03-23 13:05 UTC, erzetpe approved these changes, later dismissed

2022-03-23 14:33 UTC, przemyslavic commented
/azp run

2022-03-24 12:25 UTC, seriva submitted a review, later dismissed

2022-03-24 12:29 UTC, erzetpe submitted a review, later dismissed

2022-03-24 13:21 UTC, przemyslavic commented
/azp run

2022-03-28 07:15 UTC, przemyslavic commented
/azp run

2022-03-28 07:28 UTC, przemyslavic commented
/azp run

2022-03-28 10:28 UTC, przemyslavic approved these changes

2022-03-28 10:42 UTC, atsikham approved these changes

2022-03-28 10:45 UTC, merged