Add automatic backup creation for download requirements (#2991)
epiphany-platform/epiphany pull request #2994
Opened 2022-02-28 10:24 UTC by sbbroot

* add backup creation mechenism

* fix prepare dir name

2022-02-28 12:36 UTC, seriva submitted a review, later dismissed

2022-02-28 12:37 UTC, przemyslavic commented
/azp run

2022-02-28 13:08 UTC, rafzei submitted a review, later dismissed

2022-03-01 10:18 UTC, to-bar requested changes, later dismissed

2022-03-01 10:18 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/mode/base_mode.py
> +        Create a backup for the system repository files under the /etc directory.
```suggestion
        Create a backup of package repository files under the /etc directory.
```

2022-03-01 10:18 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/config.py
> +        self.dest_backup_created: Path
Please rename these fields since current names suggest they are rather Boolean than Path.

2022-03-01 11:56 UTC, przemyslavic commented
/azp run

2022-03-01 12:21 UTC, seriva submitted a review, later dismissed

2022-03-03 12:04 UTC, przemyslavic commented
/azp run

2022-03-03 13:37 UTC, przemyslavic commented
/azp run

2022-03-04 08:30 UTC, przemyslavic commented
/azp run

2022-03-04 10:37 UTC, przemyslavic approved these changes

2022-03-04 11:12 UTC, seriva approved these changes

2022-03-04 11:14 UTC, merged