Add image-registry configuration reading (#3106)
epiphany-platform/epiphany pull request #3159
Opened 2022-05-23 14:01 UTC by sbbroot

2022-05-25 14:21 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/config/config.py
> +        :param requirements: parsed requirements which will be filtered based on the `manifest` output
```suggestion
        :param requirements: parsed requirements which will be filtered based on the `manifest` content
```

2022-05-25 14:21 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/config/manifest_reader.py
> +            raise CriticalError(f'ManifestReader - could not find documents: {parsed_docs ^ required_docs}')
```suggestion
            raise CriticalError(f'ManifestReader - could not find document(s): {parsed_docs ^ required_docs}')
```

2022-05-26 15:43 UTC, to-bar commented
Please consider:
1) changing `detected` to `requested` since those values are just read from manifest (config file) not by gathering facts or running a command
2) printing everything when run with `--log-level=debug` without need to add `--verbose`

2022-05-26 15:43 UTC, to-bar commented
Please consider:
1) changing `detected` to `requested` since those values are just read from manifest (config file) not by gathering facts or running a command
2) printing everything when run with `--log-level=debug` without need to add `--verbose`

2022-05-26 15:55 UTC, sbbroot commented
> Please consider:
> 
>     1. changing `detected` to `requested` since those values are just read from manifest (config file) not by gathering facts or running a command
> 
>     2. printing everything when run with `--log-level=debug` without need to add `--verbose`

done.

2022-05-27 10:35 UTC, to-bar requested changes

2022-05-27 10:35 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/requirements/x86_64/images.yml
> +  default:
```suggestion
  image-registry:
```

2022-05-27 10:35 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/mode/base_mode.py
> +        for image_category in images:  # kubernetes, rabbitmq, etc.
```suggestion
        for image_group in images:  # kubernetes-master, rabbitmq, etc.
```

2022-05-27 10:35 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/tests/data/config.py
> +  default:
```suggestion
  image-registry:
```

2022-05-27 10:35 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/tests/data/config.py
> +  kubernetes:
```suggestion
  kubernetes-master:
```

2022-05-27 10:35 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/requirements/x86_64/images.yml
> +  kubernetes:
```suggestion
  kubernetes-master:
```

2022-05-27 10:35 UTC, to-bar commented on schema/common/defaults/configuration/image-registry.yml
> +        applications:
After this change I think we need to adjust Ansible code (`image_registry` and `repository` roles) where `specification.images_to_load` is used.

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +        available_images: "{{ available_images + [item] }}"
```suggestion
        requested_images: "{{ available_images + [item] }}"
```

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +    - name: Unpack current images
Please rename tasks

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +      loop: "{{ current_images_to_unpack | dict2items }}"
Please consider avoiding `loop`

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/download/tasks/list_files.yml
> +  import_tasks: list_requirements.yml
```suggestion
  include_tasks: list_requirements.yml
```

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +      when: "{{ item.file_name in list_images_result }}"
It would be nice to have a comment here

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/config/config.py
> +        # prepare image categories:
```suggestion
        # prepare image groups:
```

2022-06-02 15:06 UTC, to-bar commented on ansible/playbooks/roles/repository/files/download-requirements/src/config/manifest_reader.py
> +    def __parse_image_registry_info(self, image_registry_doc: Dict):
```suggestion
    def __parse_image_registry_doc(self, image_registry_doc: Dict):
```

2022-06-02 15:06 UTC, to-bar commented on cli/src/Config.py
> +        def input_file_name(self):
```suggestion
        def input_file_path(self):
```

2022-06-02 15:06 UTC, to-bar commented on schema/common/validation/configuration/image-registry.yml
> +              [applications, rabbitmq, kubernetes, postgresql, rook]:
```suggestion
              [applications, rabbitmq, kubernetes-master, postgresql, rook]:
```

2022-06-03 14:07 UTC, to-bar commented on ansible/playbooks/filter_plugins/container.py
> +    def flatten_list(self, data: List[List[Any]]) -> Any:
Does it differ from Ansible `flatten` filter?
https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#managing-list-variables

2022-06-03 14:07 UTC, to-bar commented on ansible/playbooks/roles/download/tasks/list_files.yml
> +- name: Set files facts
```suggestion
- name: Set files in repository as fact
```

2022-06-03 14:07 UTC, to-bar commented on ansible/playbooks/roles/download/tasks/list_images.yml
> +- name: Set images facts
```suggestion
- name: Set images in repository as fact
```

2022-06-03 14:07 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +    - name: Initialize image containers
```suggestion
    - name: Initialize image facts
```

2022-06-03 14:07 UTC, to-bar commented on ansible/playbooks/roles/image_registry/tasks/main.yml
> +      set_fact:  # gather only images listed in schema, this is needed to avoid downloading wrong files
```suggestion
      set_fact:  # gather only images listed in schema to avoid downloading unknown files
```

2022-06-06 06:12 UTC, sbbroot commented on ansible/playbooks/filter_plugins/container.py
> +    def flatten_list(self, data: List[List[Any]]) -> Any:
No it does not, I'll use the builtin

2022-06-07 08:33 UTC, to-bar approved these changes

2022-06-07 08:50 UTC, seriva approved these changes

2022-06-07 10:37 UTC, merged