Allow excluding test groups
epiphany-platform/epiphany pull request #3202
Opened 2022-06-24 18:47 UTC by to-bar

2022-06-28 07:30 UTC, seriva requested changes

2022-06-28 07:30 UTC, seriva commented on cli/src/commands/Test.py
> +            raise Exception('No test group to test')
`No test group specified to run`  maybe? As your not testing a test group but running a test group to test.

2022-06-28 07:30 UTC, seriva commented on cli/src/helpers/argparse_helpers.py
> +
Maybe add some comments while refactoring this?

2022-06-28 08:46 UTC, seriva approved these changes

2022-06-29 10:07 UTC, sbbroot approved these changes

2022-06-29 10:52 UTC, merged