Provide kubeconfig file for spec tests
epiphany-platform/epiphany pull request #3206
Opened 2022-07-01 18:06 UTC by to-bar

2022-07-01 18:07 UTC, to-bar commented
/azp run

2022-07-05 21:18 UTC, to-bar commented
/azp run

2022-07-06 07:26 UTC, seriva approved these changes, later dismissed

2022-07-07 10:57 UTC, to-bar commented
/azp run

2022-07-07 11:01 UTC, sbbroot requested changes

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +
remove endline

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +    def __get_selected_test_groups(self) -> list[str]:
```python
-> list[str]:
```
This is not officially supported with < python3.10
I suggest to stick with the `List` type from the `typing` module.

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +            selected_groups = ['all']
Make it a single line:

```python
selected_groups = ['all'] if 'all' in self.included_groups else self.included_groups
```

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +                included_groups = self.available_groups
```python
included_groups = self.available_groups if 'all' in self.included_groups else self.included_groups
```

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +            self.ansible_command = AnsibleCommand()
Declaring new object members not in a constructor is probably a bad idea.

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +                                              extra_vars=[f'kubeconfig_remote_path={self.kubeconfig_remote_path}'])
```python
            AnsibleCommand().run_playbook(inventory=self.inventory_path,
                                                                  playbook_path=playbook_path,
                                                                  extra_vars=[f'kubeconfig_remote_path={self.kubeconfig_remote_path}'])
```

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
> +            self.ansible_command.run_playbook(inventory=self.inventory_path,
Same as in `prepare_env()`

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
>          else:
```python 
else
```
Not needed, if we will not reach the `if` statement this method will always raise an exception.
Line 71/110 will never be reached.

2022-07-07 11:01 UTC, sbbroot commented on cli/src/commands/Test.py
>  import os
It would be nice to add some pydoc to this module.

2022-07-07 11:13 UTC, to-bar commented on cli/src/commands/Test.py
> +    def __get_selected_test_groups(self) -> list[str]:
`epicli` image is based on `python:3.10-slim` image.

2022-07-07 11:32 UTC, to-bar commented on cli/src/commands/Test.py
> +            self.ansible_command = AnsibleCommand()
The idea was to have lazy init, since the object is needed conditionally - based on result from `__is_env_preparation_needed()`.

2022-07-07 12:36 UTC, to-bar commented on cli/src/commands/Test.py
>  import os
Added.

2022-07-07 12:37 UTC, to-bar commented
/azp run

2022-07-07 13:19 UTC, sbbroot approved these changes

2022-07-08 09:52 UTC, seriva approved these changes

2022-07-08 09:54 UTC, merged