k8s: controller managed attachment and detachment #3190
epiphany-platform/epiphany pull request #3237
Opened 2022-07-29 15:04 UTC by cicharka

* enable configuration of `enable-controller-attach-detach`
  kubelet parameter in input manifest
* set `enable-controller-attach-detach` to `true`
* fix extend-kubeadm-config.yml task in order to keep
  consistent values in configMaps and kubeadm-config.yml
* move get and set cluster version utils to kubernetes_common

Signed-off-by: cicharka <arkadiusz.cichon@outlook.com>

2022-08-02 08:18 UTC, to-bar requested changes

2022-08-02 08:18 UTC, to-bar commented on ansible/playbooks/roles/kubernetes_common/tasks/extend-kubeadm-config.yml
> +    jsonpath: >-
```suggestion
      --output=jsonpath={{ _jsonpath }}
  vars:
    _jsonpath: >-
```

2022-08-02 08:18 UTC, to-bar commented on docs/home/howto/kubernetes/PERSISTENT_STORAGE.md
> +*Note*: In Epiphany v2.0.0 `--enable-controller-attach-detach` parameter is set by default to `false`. In order to change its value, manual steps on each of affected kubernetes nodes are required:
```suggestion
Rook requires Kubelet parameter `--enable-controller-attach-detach` set to `true`. From Epiphany v2.0.1 by default this parameter is set to `true`. Users who would like to change its value, can achieve that by modifying `specification.advanced.enable_controller_attach_detach` setting in `configuration/kubernetes-master` doc.
*Note*: In Epiphany v2.0.0 `--enable-controller-attach-detach` parameter is set by default to `false`. In order to change its value, manual steps on each affected Kubernetes node are required:
```

2022-08-02 11:02 UTC, to-bar commented on docs/home/howto/kubernetes/PERSISTENT_STORAGE.md
> +*Note*: In Epiphany v2.0.0 `--enable-controller-attach-detach` parameter is set by default to `false`. In order to change its value, manual steps on each of affected kubernetes node are required:
```suggestion
Rook requires Kubelet parameter `--enable-controller-attach-detach` set to `true`. From Epiphany v2.0.1 by default this parameter is set to `true`. Users who would like to change its value, can achieve that by modifying `specification.advanced.enable_controller_attach_detach` setting in `configuration/kubernetes-master` doc.
*Note*: In Epiphany v2.0.0 `--enable-controller-attach-detach` parameter is set by default to `false`. In order to change its value, manual steps on each of affected Kubernetes node are required:
```

2022-08-02 11:50 UTC, to-bar approved these changes, later dismissed

2022-08-02 12:07 UTC, seriva approved these changes, later dismissed

2022-08-04 10:34 UTC, przemyslavic commented
/azp run

2022-08-04 17:22 UTC, tomasz-baran approved these changes

2022-08-05 08:02 UTC, seriva approved these changes

2022-08-08 10:09 UTC, przemyslavic approved these changes

2022-08-08 10:15 UTC, merged