Refactor manifest file handling in cli (#3186)
epiphany-platform/epiphany pull request #3254
Opened 2022-08-10 18:00 UTC by sbbroot

* Create the ManifestReader class for handling configuraton data used by
  the epicli

* Rename all of the manifest variables to input/output_manifest

2022-08-16 15:02 UTC, tomasz-baran commented on cli/src/ansible/AnsibleVarsGenerator.py
> +        except IndexError:
Can we have a manifest without `epiphany-cluster` kind here? If not, IMO it's better to not "hide" the exception here.

2022-08-18 09:28 UTC, seriva reviewed
Is there any documentation that needs to have the update from --file > --input-manifest ?

2022-08-19 10:36 UTC, sbbroot commented
> Is there any documentation that needs to have the update from --file > --input-manifest ?

I didn't find anything related to the `--file` flag in our documentation.

2022-08-22 07:50 UTC, seriva submitted a review, later dismissed

2022-08-23 07:41 UTC, tomasz-baran submitted a review, later dismissed

2022-08-23 09:07 UTC, tomasz-baran approved these changes, later dismissed

2022-08-23 09:10 UTC, seriva approved these changes, later dismissed

2022-08-23 09:11 UTC, przemyslavic commented
/azp run

2022-08-23 09:31 UTC, seriva approved these changes, later dismissed

2022-08-24 14:27 UTC, tomasz-baran requested changes

2022-08-24 14:27 UTC, tomasz-baran commented on cli/epicli.py
> +    required.add_argument('-f', '--input-manifest', dest='input_manifest', type=str, required=True,
After this change import of Path (line 11) is useless.

2022-08-25 08:02 UTC, seriva approved these changes, later dismissed

2022-08-25 08:05 UTC, tomasz-baran approved these changes, later dismissed

2022-08-25 08:11 UTC, przemyslavic commented
/azp run

2022-08-25 14:56 UTC, przemyslavic commented
/azp run

2022-08-26 07:29 UTC, przemyslavic commented
/azp run

2022-08-26 12:20 UTC, seriva submitted a review, later dismissed

2022-08-29 10:47 UTC, przemyslavic commented
/azp run

2022-09-05 07:27 UTC, przemyslavic commented
/azp run

2022-09-05 13:48 UTC, przemyslavic commented
/azp run

2022-09-06 10:33 UTC, przemyslavic commented
/azp run

2022-09-06 12:55 UTC, przemyslavic commented
/azp run

2022-09-06 13:50 UTC, przemyslavic commented
/azp run

2022-09-07 10:24 UTC, przemyslavic commented
/azp run

2022-09-07 11:36 UTC, przemyslavic commented
/azp run

2022-09-07 12:53 UTC, przemyslavic commented
/azp run

2022-09-07 14:13 UTC, przemyslavic approved these changes

2022-09-08 07:10 UTC, seriva approved these changes

2022-09-08 07:10 UTC, merged